"""The main words on screen in 5 languages (tab names, main buttons, consent). Picked with "🌍 App language".

Short, everyday words on purpose. ⚠️ Pidgin/Yoruba/Hausa/Igbo written by a non-native speaker: have native speakers
check and fix this file (one place for all of it). Anything not listed here stays in English.
"""
LANGS = ["English", "Pidgin", "Yoruba", "Hausa", "Igbo"]

UI = {
    "tab_talk": ["💬 Talk to TradeVoice", "💬 Yarn with TradeVoice", "💬 Bá TradeVoice sọ̀rọ̀", "💬 Yi hira da TradeVoice",
                 "💬 Gwa TradeVoice okwu"],
    "tab_speak": ["🎙️ Speak", "🎙️ Talk am", "🎙️ Sọ̀rọ̀", "🎙️ Yi magana", "🎙️ Kwuo okwu"],
    "tab_snap": ["📸 Snap your book", "📸 Snap your book", "📸 Ya fọ́tò ìwé rẹ", "📸 Ɗauki hoton littafinka",
                 "📸 See foto akwụkwọ gị"],
    "tab_today": ["📊 Today", "📊 Today", "📊 Òní", "📊 Yau", "📊 Taa"],
    "tab_owes": ["📒 Who owes me / who I owe", "📒 Who dey owe me / who I owe", "📒 Gbèsè", "📒 Bashi", "📒 Ụgwọ"],
    "tab_insights": ["🔮 Insights", "🔮 Wetin dey come", "🔮 Ìmọ̀ràn", "🔮 Shawarwari", "🔮 Ndụmọdụ"],
    "tab_ask": ["💬 Ask my book", "💬 Ask your book", "💬 Béèrè lọ́wọ́ ìwé rẹ", "💬 Tambayi littafinka",
                "💬 Jụọ akwụkwọ gị"],
    "tab_credit": ["🏦 Credit profile", "🏦 Your record for loan", "🏦 Àkọsílẹ̀ fún owó yíyá", "🏦 Bayanan rance",
                   "🏦 Ndekọ maka mbinye ego"],
    "tab_data": ["🔒 My data", "🔒 My data", "🔒 Àkọsílẹ̀ mi", "🔒 Bayanaina", "🔒 Data m"],
    "process": ["Process", "Check am", "Ṣàyẹ̀wò", "Duba", "Lelee"],
    "confirm": ["✅ Confirm & save", "✅ Correct, save am", "✅ Ó tọ̀nà, kọ ọ́ sílẹ̀", "✅ Daidai ne, adana",
                "✅ Ọ dị mma, chekwaa"],
    "read": ["🔊 Read it to me", "🔊 Read am for me", "🔊 Kà á fún mi", "🔊 Karanta min", "🔊 Gụọrọ m ya"],
    "ask": ["Ask", "Ask", "Béèrè", "Tambaya", "Jụọ"],
    "refresh": ["🔄 Refresh", "🔄 Refresh", "🔄 Tún un wò", "🔄 Sabunta", "🔄 Megharịa"],
    "voice_note": ["Voice note", "Voice note", "Ohùn", "Saƙon murya", "Ozi olu"],
    "type_it": ["…or type it", "…or type am", "…tàbí kọ ọ́", "…ko rubuta", "…ma ọ bụ dee ya"],
    # ---- web app (web/): words on the WhatsApp-style screens
    "nav_talk": ["Chat", "Chat", "Ìjíròrò", "Hira", "Nkata"],
    "nav_book": ["Book", "Book", "Ìwé", "Littafi", "Akwụkwọ"],
    "nav_debts": ["Debts", "Debts", "Gbèsè", "Bashi", "Ụgwọ"],
    "nav_insights": ["Insights", "Wetin dey come", "Ìmọ̀ràn", "Shawarwari", "Ndụmọdụ"],
    "nav_profile": ["Profile", "Profile", "Àkọsílẹ̀", "Bayanai", "Ndekọ"],
    "online": ["online · hears English, Pidgin, Yoruba, Hausa, Igbo", "online · e dey hear English, Pidgin, Yoruba, "
               "Hausa, Igbo", "wà lórí ayélujára", "yana kan layi", "nọ n'ịntanetị"],
    "message": ["Message", "Message", "Kọ ọ̀rọ̀", "Rubuta saƙo", "Dee ozi"],
    "hold": ["Hold 🎤 to talk", "Hold 🎤 make you talk", "Tẹ 🎤 mọ́lẹ̀ láti sọ̀rọ̀", "Riƙe 🎤 don yin magana",
             "Jide 🎤 ka i kwuo okwu"],
    "recording": ["Recording… let go to send", "I dey record… leave am make e send", "Ó ń gbà ohùn… fi sílẹ̀ láti fi ránṣẹ́",
                  "Ana nadi… saki don aika", "A na-edekọ… hapụ ka o ziga"],
    "tap_send": ["Tap 🎤 again to send · tap here to cancel", "Tap 🎤 again make e send · tap here to cancel",
                 "Tẹ 🎤 lẹ́ẹ̀kan sí i láti fi ránṣẹ́", "Sake taɓa 🎤 don aikawa", "Pịa 🎤 ọzọ ka o ziga"],
    "i_speak": ["I'm speaking", "I dey talk", "Mo ń sọ", "Ina magana da", "Ana m asụ"],
    "yes_save": ["✅ Yes, save", "✅ Yes, save am", "✅ Bẹ́ẹ̀ni, kọ ọ́", "✅ Eh, adana", "✅ Ee, chekwaa"],
    "no": ["❌ No", "❌ No", "❌ Rárá", "❌ A'a", "❌ Mba"],
    "hello": ["Hello 👋 I'm your book. Tell me what you sold, who owes you, or ask me anything. Hold 🎤 to talk, or 📎 "
              "to snap your notebook.",
              "Hello 👋 Na me be your book. Tell me wetin you sell, who dey owe you, or ask me anything. Hold 🎤 make "
              "you talk, or 📎 to snap your book.",
              "Ẹ n lẹ́ o 👋 Èmi ni ìwé rẹ. Sọ ọjà tí o tà, ẹni tó jẹ ọ́, tàbí béèrè ohunkóhun. Tẹ 🎤 mọ́lẹ̀ láti sọ̀rọ̀, "
              "tàbí 📎 láti ya fọ́tò ìwé rẹ.",
              "Sannu 👋 Ni ne littafinka. Faɗa min abin da ka sayar, wanda ke da bashinka, ko ka tambaye ni komai. "
              "Riƙe 🎤 don yin magana, ko 📎 don ɗaukar hoton littafinka.",
              "Ndewo 👋 Abụ m akwụkwọ gị. Gwa m ihe i rere, onye ji gị ụgwọ, ma ọ bụ jụọ m ihe ọ bụla. Jide 🎤 ka i "
              "kwuo okwu, ma ọ bụ 📎 iji see foto akwụkwọ gị."],
    "reading_photo": ["Reading your photo…", "I dey read your photo…", "Mo ń ka fọ́tò rẹ…", "Ina karanta hotonka…",
                      "A na m agụ foto gị…"],
    "save_ticked": ["✅ Save ticked", "✅ Save the ones wey I tick", "✅ Kọ àwọn tí mo yàn", "✅ Adana waɗanda aka zaɓa",
                    "✅ Chekwaa ndị a họrọ"],
    "sold": ["Sold", "Sell", "Ọjà tí o tà", "An sayar", "Ire"],
    "spent": ["Spent", "Spend", "Owó tí o ná", "An kashe", "Mmefu"],
    "came_in": ["Came in", "Enter hand", "Owó tó wọlé", "Ya shigo", "Batara"],
    "recent": ["Recent", "Wetin you write last", "Àkọsílẹ̀ tuntun", "Na baya-bayan nan", "Nke ọhụrụ"],
    "owe_me": ["Owe me", "Dey owe me", "Wọ́n jẹ mí", "Bashina", "Ji m ụgwọ"],
    "i_owe": ["I owe", "I dey owe", "Mo jẹ", "Ina da bashi", "Ana m ji ụgwọ"],
    "remind": ["Remind", "Remind am", "Rán létí", "Tunatar", "Chetara"],
    "days_late": ["{n} days late", "{n} days late", "Ọjọ́ {n} ti kọjá", "Kwanaki {n} a makare", "Ụbọchị {n} agafeela"],
    "on_time": ["on time", "e never reach", "kò tíì pẹ́", "a kan lokaci", "n'oge"],
    "next_week": ["Next 7 days", "Next 7 days", "Ọjọ́ méje tó ń bọ̀", "Kwanaki 7 masu zuwa", "Ụbọchị 7 na-abịa"],
    "busiest": ["Busiest day", "Day wey market dey move pass", "Ọjọ́ tí ọjà ń tà jù", "Ranar da aka fi sayarwa",
                "Ụbọchị ahịa kacha aga"],
    "best_sellers": ["Best sellers", "Wetin dey sell pass", "Ọjà tó ń tà jù", "Kayan da aka fi sayarwa",
                     "Ihe kacha ere"],
    "score": ["Record score", "Record score", "Àmì àkọsílẹ̀", "Makin bayanai", "Akara ndekọ"],
    "statement": ["⬇️ Statement for lender / cooperative", "⬇️ Statement for loan people / cooperative",
                  "⬇️ Ìwé fún ẹni tó ń yáni lówó", "⬇️ Takarda don mai ba da rance", "⬇️ Akwụkwọ maka ndị na-agbazinye ego"],
    "welcome": ["Welcome to TradeVoice", "Welcome to TradeVoice", "Ẹ káàbọ̀ sí TradeVoice", "Barka da zuwa TradeVoice",
                "Nnọọ na TradeVoice"],
    "agree": ["Agree and continue", "I gree, make we go", "Mo gbà, ẹ jẹ́ ká lọ", "Na yarda, mu ci gaba",
              "Ekwere m, ka anyị gaa"],
    "app_language": ["App language", "App language", "Èdè", "Harshe", "Asụsụ"],
    "shop_name": ["Shop name", "Shop name", "Orúkọ ṣọ́ọ̀bù", "Sunan shago", "Aha ụlọ ahịa"],
    "my_data": ["My data", "My data", "Àkọsílẹ̀ mi", "Bayanaina", "Data m"],
    # ---- customers + conversations, settings, shared words (web/ and WhatsApp). Same term = same key everywhere.
    "nav_customers": ["Customers", "Customers", "Oníbàárà", "Abokan ciniki", "Ndị ahịa"],
    "you": ["You", "You", "Ìwọ", "Kai", "Gị"],
    "settings": ["Settings", "Settings", "Ètò", "Saituna", "Ntọala"],
    "language": ["Language", "Language", "Èdè", "Harshe", "Asụsụ"],
    "all": ["All", "All", "Gbogbo", "Duka", "Niile"],
    "late": ["Late", "Don late", "Ti pẹ́", "An makara", "Agafeela"],
    "search": ["Search customers", "Find customer", "Wá oníbàárà", "Nemo abokin ciniki", "Chọọ onye ahịa"],
    "new_customer": ["New customer", "New customer", "Oníbàárà tuntun", "Sabon abokin ciniki", "Onye ahịa ọhụrụ"],
    "name": ["Name", "Name", "Orúkọ", "Suna", "Aha"],
    "phone": ["Phone number", "Phone number", "Nọ́mbà fóònù", "Lambar waya", "Nọmba ekwentị"],
    "notes": ["Notes", "Notes", "Àkíyèsí", "Bayani", "Ndetu"],
    "save": ["Save", "Save", "Fi pamọ́", "Adana", "Chekwaa"],
    "cancel": ["Cancel", "Cancel", "Fagilé", "Soke", "Kagbuo"],
    "edit": ["Edit", "Edit", "Ṣàtúnṣe", "Gyara", "Dezie"],
    "delete": ["Delete", "Delete", "Paárẹ́", "Goge", "Hichapụ"],
    "back": ["Back", "Back", "Padà", "Koma", "Laghachi"],
    "record_payment": ["Record payment", "Write payment", "Kọ owó tí wọ́n san", "Rubuta biya", "Dee ụgwọ a kwụrụ"],
    "record_sale": ["Record sale", "Write sale", "Kọ ọjà tí o tà", "Rubuta sayarwa", "Dee ahịa"],
    "prepare_reminder": ["Prepare reminder", "Write reminder", "Kọ ìránnilétí", "Shirya tunatarwa", "Kwadebe ncheta"],
    "edit_contact": ["Edit contact", "Edit contact", "Ṣàtúnṣe olùbáṣepọ̀", "Gyara bayanai", "Dezie kọntaktị"],
    "open_whatsapp": ["Open WhatsApp", "Open WhatsApp", "Ṣí WhatsApp", "Buɗe WhatsApp", "Mepee WhatsApp"],
    "edit_message": ["Edit message", "Edit message", "Ṣàtúnṣe ọ̀rọ̀", "Gyara saƙo", "Dezie ozi"],
    "draft_note": ["TradeVoice prepared this. You send it yourself.", "TradeVoice write am. Na you go send am.",
                   "TradeVoice ló kọ èyí. Ìwọ ni yóò fi ránṣẹ́.", "TradeVoice ne ya rubuta. Kai za ka aika.",
                   "TradeVoice dere ya. Ọ bụ gị ga-ezipu ya."],
    "opened_note": ["Opened in WhatsApp", "Don open for WhatsApp", "Ti ṣí i ní WhatsApp", "An buɗe a WhatsApp",
                    "Emepere ya na WhatsApp"],
    "no_phone": ["No phone saved. WhatsApp will ask you to choose the contact.",
                 "No phone number. WhatsApp go ask you to pick the person.",
                 "Kò sí nọ́mbà fóònù. WhatsApp yóò ní kí o yan ẹni náà.",
                 "Babu lambar waya. WhatsApp zai tambaye ka ka zaɓi mutumin.",
                 "Enweghị nọmba ekwentị. WhatsApp ga-ajụ gị ka ị họrọ onye ahụ."],
    "add_phone": ["Add phone", "Add phone", "Fi nọ́mbà kún un", "Ƙara lamba", "Tinye nọmba"],
    "owes_you": ["owes you {m}", "dey owe you {m}", "jẹ ọ́ {m}", "yana bin ka {m}", "ji gị {m}"],
    "you_owe": ["you owe {m}", "you dey owe {m}", "o jẹ {m}", "kana bin sa {m}", "i ji {m}"],
    "paid_up": ["Paid up", "Don pay finish", "Ti san tán", "Ya biya duka", "Akwụchaala"],
    "due": ["Due {d}", "Go pay {d}", "Yóò san ní {d}", "Zai biya {d}", "Ga-akwụ {d}"],
    "last_item": ["Last: {x}", "Last: {x}", "Ìkẹyìn: {x}", "Na ƙarshe: {x}", "Nke ikpeazụ: {x}"],
    "note_hint": ["Write a note, or what happened (e.g. paid 10k)", "Write note, or wetin happen (e.g. paid 10k)",
                  "Kọ àkíyèsí, tàbí ohun tó ṣẹlẹ̀ (bí paid 10k)", "Rubuta bayani, ko abin da ya faru (misali paid 10k)",
                  "Dee ndetu, ma ọ bụ ihe mere (dịka paid 10k)"],
    "amount": ["Amount (₦)", "Amount (₦)", "Iye owó (₦)", "Adadi (₦)", "Ego (₦)"],
    "item": ["Item", "Wetin you sell", "Ọjà", "Kaya", "Ihe"],
    "paid_now": ["Paid now", "Pay now", "Ó san báyìí", "An biya yanzu", "Akwụọla ugbu a"],
    "on_credit": ["On credit", "On credit", "Àwìn", "Bashi", "Ụgwọ"],
    "will_pay": ["Will pay", "Go pay", "Yóò san", "Zai biya", "Ga-akwụ"],
    "none": ["None", "None", "Kò sí", "Babu", "Ọ dịghị"],
    "today": ["Today", "Today", "Òní", "Yau", "Taa"],
    "yesterday": ["Yesterday", "Yesterday", "Àná", "Jiya", "Ụnyaahụ"],
    "tomorrow": ["Tomorrow", "Tomorrow", "Ọ̀la", "Gobe", "Echi"],
    "friday": ["Friday", "Friday", "Ẹtì", "Juma'a", "Fraịdee"],
    "customer_deleted": ["This customer was deleted.", "Dem don delete this customer.", "A ti pa oníbàárà yìí rẹ́.",
                         "An goge wannan abokin ciniki.", "Ehichapụla onye ahịa a."],
    "confirm_delete_customer": [
        "Delete this customer and the conversation? Their records stay in your book.",
        "Delete this customer and the chat? Wetin you don write for book go remain.",
        "Ṣé kí a pa oníbàárà yìí àti ìjíròrò rẹ̀ rẹ́? Àkọsílẹ̀ owó rẹ̀ yóò wà nínú ìwé rẹ.",
        "A goge abokin ciniki da hirar? Bayanan kuɗinsa za su zauna a littafinka.",
        "Hichapụ onye ahịa a na nkata ya? Ndekọ ego ya ga-anọgide n'akwụkwọ gị."],
    "no_customers": ["No customers yet. They appear here when you record a sale, a debt or a payment with a name.",
                     "No customer yet. Dem go show here when you write sale, debt or payment with name.",
                     "Kò sí oníbàárà síbẹ̀. Wọn yóò hàn níbí nígbà tí o bá kọ ọjà, gbèsè tàbí owó tí wọ́n san pẹ̀lú orúkọ.",
                     "Babu abokin ciniki tukuna. Za su bayyana nan idan ka rubuta sayarwa, bashi ko biya da suna.",
                     "Enweghị onye ahịa ugbu a. Ha ga-apụta ebe a mgbe i dere ahịa, ụgwọ ma ọ bụ ịkwụ ụgwọ nwere aha."],
    "empty_thread": ["Nothing here yet. Record a sale or a payment for {n}.",
                     "Nothing dey here yet. Write sale or payment for {n}.",
                     "Kò sí nǹkan níbí síbẹ̀. Kọ ọjà tàbí owó tí {n} san.",
                     "Babu komai nan tukuna. Rubuta sayarwa ko biyan {n}.",
                     "Ọ dịghị ihe ebe a. Dee ahịa ma ọ bụ ịkwụ ụgwọ maka {n}."],
    "t_sale": ["Sold (paid)", "Sell (dem pay)", "Tà (wọ́n san)", "An sayar (an biya)", "Rere (akwụọla)"],
    "t_credit_sale": ["Sold on credit", "Sell on credit", "Tà ní àwìn", "An sayar bashi", "Rere n'ụgwọ"],
    "t_payment_received": ["Paid me", "Pay me", "San owó fún mi", "Ya biya ni", "Kwụrụ m"],
    "t_expense": ["Spent", "Spend", "Ná owó", "An kashe", "Mefuru"],
    "t_credit_purchase": ["Bought on credit (I owe)", "Buy on credit (I owe)", "Rà ní àwìn (mo jẹ)",
                          "An saya bashi (ina bin)", "Zụtara n'ụgwọ (a na m ji)"],
    "t_payment_made": ["I paid back", "I pay back", "Mo san padà", "Na biya", "Akwụghachiri m"],
    "error": ["Something went wrong. Please try again.", "Something no work. Abeg try again.",
              "Nǹkan kan ò ṣiṣẹ́. Jọ̀wọ́ gbìyànjú lẹ́ẹ̀kan sí i.", "Wani abu ya faru. Da fatan a sake gwadawa.",
              "Ihe adịghị mma. Biko nwaa ọzọ."],
    "offline": ["Can't reach TradeVoice. Check your internet.", "TradeVoice no dey reach. Check your data.",
                "Kò lè dé TradeVoice. Ṣàyẹ̀wò ayélujára rẹ.", "Ba a iya kaiwa TradeVoice ba. Duba intanet ɗinka.",
                "Enweghị ike iru TradeVoice. Lelee ịntanetị gị."],
    "saved_n": ["Saved {n}.", "Don save {n}.", "Ti fi {n} pamọ́.", "An adana {n}.", "Echekwara {n}."],
    "check_save": ["Check, then save", "Check am, then save", "Ṣàyẹ̀wò, kí o tó fi pamọ́", "Duba, sannan ka adana",
                   "Lelee, mgbe ahụ chekwaa"],
    "empty_book": ["Nothing yet. Go to Chat and tell me a sale.", "Nothing yet. Go Chat, tell me wetin you sell.",
                   "Kò sí nǹkan síbẹ̀. Lọ sí Ìjíròrò kí o sọ ọjà tí o tà.", "Babu komai tukuna. Je Hira ka faɗa min abin da ka sayar.",
                   "Ọ dịghị ihe ugbu a. Gaa na Nkata gwa m ihe i rere."],
    "cash_left": ["Cash left after normal spending", "Money wey go remain after normal spending",
                  "Owó tí yóò kù lẹ́yìn ìnáwó", "Kuɗin da zai rage bayan kashe-kashe", "Ego ga-afọdụ mgbe mmefu"],
    "stock_tip": ["Stock up the day before.", "Buy market the day before.", "Ra ọjà ní ọjọ́ tó ṣáájú.",
                  "Saya kaya kwana ɗaya kafin.", "Zụta ngwa ahịa ụbọchị tupu mgbe ahụ."],
    "promised_week": ["Promised this week", "Dem promise to pay this week", "Wọ́n ṣèlérí láti san lọ́sẹ̀ yìí",
                      "Alkawarin biya a wannan makon", "Ha kwere nkwa ịkwụ n'izu a"],
    "forecast_note": ["Forecast = your average sales for each weekday over the last 4 weeks. Simple and explainable, "
                      "not a guarantee.", "Forecast na your average sales for each day for last 4 weeks. E no be promise.",
                      "Àsọtẹ́lẹ̀ yìí jẹ́ àròpọ̀ ọjà rẹ ní ọ̀sẹ̀ mẹ́rin tó kọjá. Kì í ṣe ìdánilójú.",
                      "Hasashe = matsakaicin sayarwarka a makonni 4 da suka wuce. Ba tabbaci ba ne.",
                      "Amụma = nkezi ahịa gị n'izu anọ gara aga. Ọ bụghị nkwa."],
    "why_score": ["Why this score", "Why this score", "Ìdí àmì yìí", "Dalilin wannan maki", "Ihe kpatara akara a"],
    "score_note": ["A simple published formula over your own records, no hidden AI. It helps you talk to a lender, "
                   "cooperative or ajo group; it is not a loan decision.",
                   "Simple formula from your own book, no hidden AI. E help you talk to loan people or cooperative; "
                   "e no be loan decision.",
                   "Ìṣirò rọrùn lórí àkọsílẹ̀ rẹ, kò sí AI tí ó farapamọ́. Ó ràn ọ́ lọ́wọ́ láti bá ẹni tó ń yáni lówó sọ̀rọ̀; "
                   "kì í ṣe ìpinnu owó yíyá.",
                   "Lissafi mai sauƙi daga bayananka, babu AI a ɓoye. Yana taimaka maka magana da mai ba da rance; "
                   "ba shawarar rance ba ce.",
                   "Usoro dị mfe n'ime ndekọ gị, enweghị AI zoro ezo. Ọ na-enyere gị aka ịgwa ndị na-agbazinye ego okwu; "
                   "ọ bụghị mkpebi mbinye ego."],
    "my_year": ["My year so far", "My year so far", "Ọdún mi títí di báyìí", "Shekarata zuwa yanzu", "Afọ m ruo ugbu a"],
    "delete_all": ["Delete all my records", "Delete all my records", "Pa gbogbo àkọsílẹ̀ mi rẹ́", "Goge duk bayanaina",
                   "Hichapụ ndekọ m niile"],
    "privacy": ["Voice notes and photos are read and deleted straight away; only the records are kept. Speech is "
                "turned into text by Intron; the AI that understands your notes and reads your photos runs on our own "
                "NVIDIA Brev GPU. Nothing is saved until you say yes. Reminders are only sent if you press send.",
                "We dey read voice note and photo, then delete am sharp sharp; na only your records we dey keep. "
                "Nothing go save until you talk yes. Reminder no go send unless you press send.",
                "A máa ka ohùn àti fọ́tò, a sì pa wọ́n rẹ́ lẹ́sẹ̀kẹsẹ̀; àkọsílẹ̀ nìkan ni a ń tọ́jú. Kò sí ohun tí a ó "
                "fi pamọ́ títí o fi sọ bẹ́ẹ̀ni. Ìránnilétí kì í lọ àyàfi tí o bá tẹ̀ ẹ́.",
                "Ana karanta murya da hoto sannan a goge su nan take; bayanan kawai ake ajiyewa. Ba a adana komai "
                "sai ka ce eh. Tunatarwa ba ta tafiya sai ka danna aika.",
                "A na-agụ olu na foto ma hichapụ ha ozugbo; naanị ndekọ ka a na-edebe. Ọ dịghị ihe a na-echekwa ruo "
                "mgbe ị kwuru ee. Ncheta anaghị aga ma ọ bụrụ na ị pịaghị zipu."],
    "photo_none": ["I couldn't find money records in this photo. Try a flat page, in good light, whole page in view.",
                   "I no see money records for this photo. Try flat page, better light, whole page.",
                   "Mi ò rí àkọsílẹ̀ owó nínú fọ́tò yìí. Ya ojú ìwé tó tẹ́jú, ní ìmọ́lẹ̀ tó dára.",
                   "Ban ga bayanan kuɗi a hoton nan ba. Gwada shafi a shimfiɗe, a haske mai kyau.",
                   "Ahụghị m ndekọ ego na foto a. Nwaa peeji dị larịị, n'ìhè dị mma."],
    "photo_read": ["I read {n} lines. Check the names and amounts, untick anything wrong, then save.",
                   "I read {n} lines. Check the names and amounts, remove wetin no correct, then save.",
                   "Mo ka ìlà {n}. Ṣàyẹ̀wò orúkọ àti iye owó, yọ èyí tí kò tọ̀nà kúrò, kí o tó fi pamọ́.",
                   "Na karanta layi {n}. Duba sunaye da adadi, cire wanda bai dace ba, sannan ka adana.",
                   "Agụrụ m ahịrị {n}. Lelee aha na ego, wepụ nke na-ezighi ezi, mgbe ahụ chekwaa."],
    "cancelled": ["Cancelled", "Cancelled", "A ti fagilé", "An soke", "Akagbuola"],
    "remind_none": ["{n} doesn't owe you anything 🎉", "{n} no dey owe you 🎉", "{n} kò jẹ ọ́ ní nǹkankan 🎉",
                    "{n} ba shi da bashinka 🎉", "{n} ejighị gị ụgwọ 🎉"],
    "nobody_owes": ["Nobody owes you 🎉", "Nobody dey owe you 🎉", "Kò sí ẹni tó jẹ ọ́ 🎉", "Babu mai bin ka bashi 🎉",
                    "Onweghị onye ji gị ụgwọ 🎉"],
    "you_owe_nobody": ["You owe nobody 🎉", "You no owe anybody 🎉", "O kò jẹ ẹnikẹ́ni 🎉", "Ba ka da bashin kowa 🎉",
                       "I jighị onye ọ bụla ụgwọ 🎉"],
    "wd_0": ["Monday", "Monday", "Ajé", "Litinin", "Mọnde"],
    "wd_1": ["Tuesday", "Tuesday", "Ìṣẹ́gun", "Talata", "Tiuzdee"],
    "wd_2": ["Wednesday", "Wednesday", "Ọjọ́rú", "Laraba", "Wenezdee"],
    "wd_3": ["Thursday", "Thursday", "Ọjọ́bọ̀", "Alhamis", "Tọọzdee"],
    "wd_4": ["Friday", "Friday", "Ẹtì", "Juma'a", "Fraịdee"],
    "wd_5": ["Saturday", "Saturday", "Àbámẹ́ta", "Asabar", "Satọdee"],
    "wd_6": ["Sunday", "Sunday", "Àìkú", "Lahadi", "Sọndee"],
    "sp_Record-keeping consistency": ["Record-keeping consistency", "How often you write", "Bí o ṣe ń kọ̀wé déédéé",
                                      "Rubutu akai-akai", "Ide ndekọ mgbe niile"],
    "sp_Profitability": ["Profitability", "Profit", "Èrè", "Riba", "Uru"],
    "sp_Debt collection": ["Debt collection", "Debt wey you collect", "Gbígba gbèsè", "Karɓar bashi", "Ịnata ụgwọ"],
    "sp_History length": ["History length", "How long you don write", "Gígùn àkọsílẹ̀", "Tsawon bayanai",
                          "Ogologo ndekọ"],
    "band_Strong": ["Strong", "Strong", "Ó lágbára", "Mai ƙarfi", "Siri ike"],
    "band_Building": ["Building", "E dey grow", "Ó ń dàgbà", "Ana ginawa", "Na-eto"],
    "band_Early": ["Early", "Just start", "Ìbẹ̀rẹ̀", "Farko", "Mmalite"],
    "days_avg": ["{d} days of records · average daily sales {m}", "{d} days for book · daily sales average {m}",
                 "Ọjọ́ {d} àkọsílẹ̀ · àròpọ̀ ọjà ojoojúmọ́ {m}", "Kwanaki {d} na bayanai · matsakaicin sayarwa kullum {m}",
                 "Ụbọchị {d} nke ndekọ · nkezi ahịa kwa ụbọchị {m}"],
    "empty_insights": ["Record a few more days, then I can tell you about next week.", "Write for some more days, then I go fit tell you about next week.", "Kọ àkọsílẹ̀ fún ọjọ́ díẹ̀ sí i, lẹ́yìn náà mo lè sọ nípa ọ̀sẹ̀ tó ń bọ̀.", "Ka rubuta na wasu kwanaki, sannan zan iya faɗa maka game da makon gobe.", "Dee ihe ụbọchị ole na ole ọzọ, mgbe ahụ m ga-agwa gị maka izu na-abịa."],
    "empty_profile": ["Your book is empty. Start by recording a sale.", "Your book still empty. Start by writing one sale.", "Ìwé rẹ ṣì ṣófo. Bẹ̀rẹ̀ nípa kíkọ ọjà kan tí o tà.", "Littafinka babu komai. Fara da rubuta wani abin da aka sayar.", "Akwụkwọ gị tọgbọrọ chakoo. Bido site n'ide otu ahịa i rere."],
    # ---- public website (web/landing.html). Short lines only; longer copy stays English until checked by natives.
    "web_open": ["Open TradeVoice", "Open TradeVoice", "Ṣí TradeVoice", "Buɗe TradeVoice", "Mepee TradeVoice"],
    "web_h1": ["Keep your books.<br>Just speak.", "Keep your book.<br>Just talk am.", "Tọ́jú ìwé rẹ.<br>Kàn sọ̀rọ̀.",
               "Riƙe littafinka.<br>Kawai ka yi magana.", "Debe akwụkwọ gị.<br>Naanị kwuo okwu."],
    "web_start": ["Start keeping your books", "Start to keep your book", "Bẹ̀rẹ̀ sí í tọ́jú ìwé rẹ",
                  "Fara riƙe littafinka", "Malite idebe akwụkwọ gị"],
    "web_how": ["See how it works", "See how e dey work", "Wo bí ó ṣe ń ṣiṣẹ́", "Duba yadda yake aiki",
                "Hụ ka o si arụ ọrụ"],
    "web_how_title": ["How it works", "How e dey work", "Bí ó ṣe ń ṣiṣẹ́", "Yadda yake aiki", "Ka o si arụ ọrụ"],
    "web_features": ["Features", "Wetin e fit do", "Ohun tí ó lè ṣe", "Abin da yake yi", "Ihe ọ na-eme"],
    "web_everything": ["Everything a trader needs", "Everything wey trader need", "Gbogbo ohun tí oníṣòwò nílò",
                       "Duk abin da ɗan kasuwa ke bukata", "Ihe niile onye ahịa chọrọ"],
    "web_control": ["You stay in control.", "Na you dey control.", "Ìwọ ni ó ní àṣẹ.", "Kai ne ke da iko.",
                    "Ọ bụ gị na-achịkwa."],
    "consent": [
        "I agree that my voice note / photo is processed by AI to create my records. "
        "The audio or photo is deleted right after it is read.",
        "I gree make AI read my voice note / photo to write my records. Dem go delete the voice or photo after.",
        "Mo gbà kí AI ka ohùn tàbí fọ́tò mi láti kọ àkọsílẹ̀ mi. Wọn yóò pa ohùn tàbí fọ́tò náà rẹ́ lẹ́yìn náà.",
        "Na yarda AI ta karanta muryata ko hotona don rubuta bayanaina. Za a goge muryar ko hoton bayan haka.",
        "Ekwere m ka AI gụọ olu m ma ọ bụ foto m iji dee ndekọ m. A ga-ehichapụ ha mgbe e mechara.",
    ],
}


# Direction per language, so a right-to-left language (e.g. Arabic-script Hausa, Ajami) can be added later.
DIRECTION = {lang: "ltr" for lang in LANGS}
CODES = {"English": "en", "Pidgin": "pcm", "Yoruba": "yo", "Hausa": "ha", "Igbo": "ig"}


def t(key, lang):
    """Word for `key` in `lang`. Missing language or empty entry -> English; unknown key -> "" (never the key)."""
    values = UI.get(key)
    if not values:
        return ""
    v = values[LANGS.index(lang)] if lang in LANGS and LANGS.index(lang) < len(values) else ""
    return v or values[0]
