"""The main words on screen in 4 languages (tab names, main buttons, consent). Picked with "🌍 App language".

Languages = N-ATLaS's: English (Nigerian English), Yoruba, Hausa, Igbo. Pidgin was dropped as a CHOICE on 2 Oct
(N-ATLaS has no Pidgin model): Pidgin speakers are still heard and understood, and get English. The tables below
still hold a Pidgin column (TABLE_LANGS) so nothing shifts; it is never shown.

Short, everyday words on purpose. ⚠️ Pidgin/Yoruba/Hausa/Igbo written by a non-native speaker: have native speakers
check and fix this file (one place for all of it). Anything not listed here stays in English.
"""
TABLE_LANGS = ["English", "Pidgin", "Yoruba", "Hausa", "Igbo"]   # column order of the tables below
LANGS = ["English", "Yoruba", "Hausa", "Igbo"]                     # what a trader can choose


def choose(lang):
    """A language the app speaks: anything else (old 'Pidgin' settings, unknown) -> English."""
    return lang if lang in LANGS else "English"

UI = {
    "tab_talk": ["💬 Talk to TradeVoice", "💬 Yarn with TradeVoice", "💬 Bá TradeVoice sọ̀rọ̀", "💬 Yi hira da TradeVoice",
                 "💬 Gwa TradeVoice okwu"],
    "tab_speak": ["🎙️ Speak", "🎙️ Talk am", "🎙️ Sọ̀rọ̀", "🎙️ Yi magana", "🎙️ Kwuo okwu"],
    "tab_snap": ["📸 Snap your book", "📸 Snap your book", "📸 Ya fọ́tò ìwé rẹ", "📸 Ɗauki hoton littafinka",
                 "📸 See foto akwụkwọ gị"],
    "tab_today": ["📊 Today", "📊 Today", "📊 Òní", "📊 Yau", "📊 Taa"],
    "tab_owes": ["📒 Who owes me / who I owe", "📒 Who dey owe me / who I owe", "📒 Gbèsè", "📒 Bashi", "📒 Ụgwọ"],
    "tab_insights": ["🔮 Insights", "🔮 Wetin dey come", "🔮 Ìmọ̀ràn", "🔮 Shawarwari", "🔮 Ndụmọdụ"],
    "tab_ask": ["💬 Ask my book", "💬 Ask your book", "💬 Béèrè lọ́wọ́ ìwé rẹ", "💬 Tambayi littafinka",
                "💬 Jụọ akwụkwọ gị"],
    "tab_credit": ["🏦 Credit profile", "🏦 Your record for loan", "🏦 Àkọsílẹ̀ fún owó yíyá", "🏦 Bayanan rance",
                   "🏦 Ndekọ maka mbinye ego"],
    "tab_data": ["🔒 My data", "🔒 My data", "🔒 Àkọsílẹ̀ mi", "🔒 Bayanaina", "🔒 Data m"],
    "process": ["Process", "Check am", "Ṣàyẹ̀wò", "Duba", "Lelee"],
    "confirm": ["✅ Confirm & save", "✅ Correct, save am", "✅ Ó tọ̀nà, kọ ọ́ sílẹ̀", "✅ Daidai ne, adana",
                "✅ Ọ dị mma, chekwaa"],
    "read": ["🔊 Read it to me", "🔊 Read am for me", "🔊 Kà á fún mi", "🔊 Karanta min", "🔊 Gụọrọ m ya"],
    "ask": ["Ask", "Ask", "Béèrè", "Tambaya", "Jụọ"],
    "refresh": ["🔄 Refresh", "🔄 Refresh", "🔄 Tún un wò", "🔄 Sabunta", "🔄 Megharịa"],
    "voice_note": ["Voice note", "Voice note", "Ohùn", "Saƙon murya", "Ozi olu"],
    "type_it": ["…or type it", "…or type am", "…tàbí kọ ọ́", "…ko rubuta", "…ma ọ bụ dee ya"],
    # ---- web app (web/): words on the WhatsApp-style screens
    "nav_talk": ["Chat", "Chat", "Ìjíròrò", "Hira", "Nkata"],
    "nav_book": ["Book", "Book", "Ìwé", "Littafi", "Akwụkwọ"],
    "nav_debts": ["Debts", "Debts", "Gbèsè", "Bashi", "Ụgwọ"],
    "nav_insights": ["Insights", "Forecast", "Ìmọ̀ràn", "Hasashe", "Ndụmọdụ"],
    "nav_profile": ["Profile", "Profile", "Àkọsílẹ̀", "Bayanai", "Ndekọ"],
    "online": ["online · hears English, Pidgin, Yoruba, Hausa, Igbo", "online · e dey hear English, Pidgin, Yoruba, "
               "Hausa, Igbo", "wà lórí ayélujára", "yana kan layi", "nọ n'ịntanetị"],
    "message": ["Message", "Message", "Kọ ọ̀rọ̀", "Rubuta saƙo", "Dee ozi"],
    "hold": ["Hold 🎤 to talk", "Hold 🎤 make you talk", "Tẹ 🎤 mọ́lẹ̀ láti sọ̀rọ̀", "Riƙe 🎤 don yin magana",
             "Jide 🎤 ka i kwuo okwu"],
    "recording": ["Recording… let go to send", "I dey record… leave am make e send", "Ó ń gbà ohùn… fi sílẹ̀ láti fi ránṣẹ́",
                  "Ana nadi… saki don aika", "A na-edekọ… hapụ ka o ziga"],
    "tap_send": ["Tap 🎤 again to send · tap here to cancel", "Tap 🎤 again make e send · tap here to cancel",
                 "Tẹ 🎤 lẹ́ẹ̀kan sí i láti fi ránṣẹ́", "Sake taɓa 🎤 don aikawa", "Pịa 🎤 ọzọ ka o ziga"],
    "i_speak": ["I'm speaking", "I dey talk", "Mo ń sọ", "Ina magana da", "Ana m asụ"],
    "yes_save": ["Yes, save", "Yes, save am", "Bẹ́ẹ̀ni, kọ ọ́", "Eh, adana", "Ee, chekwaa"],
    "no": ["No", "No", "Rárá", "A'a", "Mba"],
    "hello": ["Hello 👋 I'm your book. Tell me what you sold, who owes you, or ask me anything. Hold 🎤 to talk, or 📷 "
              "to snap your notebook.",
              "Hello 👋 Na me be your book. Tell me wetin you sell, who dey owe you, or ask me anything. Hold 🎤 make "
              "you talk, or 📷 to snap your book.",
              "Ẹ n lẹ́ o 👋 Èmi ni ìwé rẹ. Sọ ọjà tí o tà, ẹni tó jẹ ọ́, tàbí béèrè ohunkóhun. Tẹ 🎤 mọ́lẹ̀ láti sọ̀rọ̀, "
              "tàbí 📷 láti ya fọ́tò ìwé rẹ.",
              "Sannu 👋 Ni ne littafinka. Faɗa min abin da ka sayar, wanda ke da bashinka, ko ka tambaye ni komai. "
              "Riƙe 🎤 don yin magana, ko 📷 don ɗaukar hoton littafinka.",
              "Ndewo 👋 Abụ m akwụkwọ gị. Gwa m ihe i rere, onye ji gị ụgwọ, ma ọ bụ jụọ m ihe ọ bụla. Jide 🎤 ka i "
              "kwuo okwu, ma ọ bụ 📷 iji see foto akwụkwọ gị."],
    "reading_photo": ["Reading your photo…", "I dey read your photo…", "Mo ń ka fọ́tò rẹ…", "Ina karanta hotonka…",
                      "A na m agụ foto gị…"],
    "save_ticked": ["Save ticked", "Save the ones wey I tick", "Kọ àwọn tí mo yàn", "Adana waɗanda aka zaɓa",
                    "Chekwaa ndị a họrọ"],
    "sold": ["Sold", "Sell", "Ọjà tí o tà", "An sayar", "Ire"],
    "spent": ["Spent", "Spend", "Owó tí o ná", "An kashe", "Mmefu"],
    "came_in": ["Came in", "Enter hand", "Owó tó wọlé", "Ya shigo", "Batara"],
    "recent": ["Recent", "Wetin you write last", "Àkọsílẹ̀ tuntun", "Na baya-bayan nan", "Nke ọhụrụ"],
    "owe_me": ["Owe me", "Dey owe me", "Wọ́n jẹ mí", "Bashina", "Ji m ụgwọ"],
    "i_owe": ["I owe", "I dey owe", "Mo jẹ", "Ina da bashi", "Ana m ji ụgwọ"],
    "remind": ["Remind", "Remind am", "Rán létí", "Tunatar", "Chetara"],
    "days_late": ["{n} days late", "{n} days late", "Ọjọ́ {n} ti kọjá", "Kwanaki {n} a makare", "Ụbọchị {n} agafeela"],
    "on_time": ["on time", "e never reach", "kò tíì pẹ́", "a kan lokaci", "n'oge"],
    "next_week": ["Next 7 days", "Next 7 days", "Ọjọ́ méje tó ń bọ̀", "Kwanaki 7 masu zuwa", "Ụbọchị 7 na-abịa"],
    "busiest": ["Busiest day", "Day wey market dey move pass", "Ọjọ́ tí ọjà ń tà jù", "Ranar da aka fi sayarwa",
                "Ụbọchị ahịa kacha aga"],
    "best_sellers": ["Best sellers", "Wetin dey sell pass", "Ọjà tó ń tà jù", "Kayan da aka fi sayarwa",
                     "Ihe kacha ere"],
    "score": ["Record score", "Record score", "Àmì àkọsílẹ̀", "Makin bayanai", "Akara ndekọ"],
    "statement": ["Statement for lender / cooperative", "Statement for loan people / cooperative",
                  "Ìwé fún ẹni tó ń yáni lówó", "Takarda don mai ba da rance", "Akwụkwọ maka ndị na-agbazinye ego"],
    "welcome": ["Welcome to TradeVoice", "Welcome to TradeVoice", "Ẹ káàbọ̀ sí TradeVoice", "Barka da zuwa TradeVoice",
                "Nnọọ na TradeVoice"],
    "agree": ["Agree and continue", "I gree, make we go", "Mo gbà, ẹ jẹ́ ká lọ", "Na yarda, mu ci gaba",
              "Ekwere m, ka anyị gaa"],
    "app_language": ["App language", "App language", "Èdè", "Harshe", "Asụsụ"],
    "shop_name": ["Shop name", "Shop name", "Orúkọ ṣọ́ọ̀bù", "Sunan shago", "Aha ụlọ ahịa"],
    "my_data": ["My data", "My data", "Àkọsílẹ̀ mi", "Bayanaina", "Data m"],
    # ---- customers + conversations, settings, shared words (web/ and WhatsApp). Same term = same key everywhere.
    "nav_customers": ["Customers", "Customers", "Oníbàárà", "Masu saye", "Ndị ahịa"],
    "you": ["You", "You", "Ìwọ", "Kai", "Gị"],
    "settings": ["Settings", "Settings", "Ètò", "Saituna", "Ntọala"],
    "language": ["Language", "Language", "Èdè", "Harshe", "Asụsụ"],
    "all": ["All", "All", "Gbogbo", "Duka", "Niile"],
    "late": ["Late", "Don late", "Ti pẹ́", "An makara", "Agafeela"],
    "search": ["Search customers", "Find customer", "Wá oníbàárà", "Nemo abokin ciniki", "Chọọ onye ahịa"],
    "new_customer": ["New customer", "New customer", "Oníbàárà tuntun", "Sabon abokin ciniki", "Onye ahịa ọhụrụ"],
    "name": ["Name", "Name", "Orúkọ", "Suna", "Aha"],
    "phone": ["Phone number", "Phone number", "Nọ́mbà fóònù", "Lambar waya", "Nọmba ekwentị"],
    "notes": ["Notes", "Notes", "Àkíyèsí", "Bayani", "Ndetu"],
    "save": ["Save", "Save", "Fi pamọ́", "Adana", "Chekwaa"],
    "cancel": ["Cancel", "Cancel", "Fagilé", "Soke", "Kagbuo"],
    "edit": ["Edit", "Edit", "Ṣàtúnṣe", "Gyara", "Dezie"],
    "delete": ["Delete", "Delete", "Paárẹ́", "Goge", "Hichapụ"],
    "back": ["Back", "Back", "Padà", "Koma", "Laghachi"],
    "record_payment": ["Record payment", "Write payment", "Kọ owó tí wọ́n san", "Rubuta biya", "Dee ụgwọ a kwụrụ"],
    "record_sale": ["Record sale", "Write sale", "Kọ ọjà tí o tà", "Rubuta sayarwa", "Dee ahịa"],
    "prepare_reminder": ["Prepare reminder", "Write reminder", "Kọ ìránnilétí", "Shirya tunatarwa", "Kwadebe ncheta"],
    "edit_contact": ["Edit contact", "Edit contact", "Ṣàtúnṣe olùbáṣepọ̀", "Gyara bayanai", "Dezie kọntaktị"],
    "open_whatsapp": ["Open WhatsApp", "Open WhatsApp", "Ṣí WhatsApp", "Buɗe WhatsApp", "Mepee WhatsApp"],
    "edit_message": ["Edit message", "Edit message", "Ṣàtúnṣe ọ̀rọ̀", "Gyara saƙo", "Dezie ozi"],
    "paid_notice": ["💸 {name} just paid ₦{amount} online. Still owes you: ₦{left}.",
                    "💸 {name} don pay ₦{amount} online. Wetin remain: ₦{left}.",
                    "💸 {name} ṣẹ̀ṣẹ̀ san ₦{amount} lórí ayélujára. Èyí tó kù: ₦{left}.",
                    "💸 {name} ya biya ₦{amount} ta yanar gizo. Saura: ₦{left}.",
                    "💸 {name} kwụrụ ₦{amount} n'ịntanetị ugbu a. Ihe fọdụrụ: ₦{left}."],
    "draft_note": ["TradeVoice prepared this. You send it yourself.", "TradeVoice write am. Na you go send am.",
                   "TradeVoice ló kọ èyí. Ìwọ ni yóò fi ránṣẹ́.", "TradeVoice ne ya rubuta. Kai za ka aika.",
                   "TradeVoice dere ya. Ọ bụ gị ga-ezipu ya."],
    "opened_note": ["Opened in WhatsApp", "Don open for WhatsApp", "Ti ṣí i ní WhatsApp", "An buɗe a WhatsApp",
                    "Emepere ya na WhatsApp"],
    "no_phone": ["No phone saved. WhatsApp will ask you to choose the contact.",
                 "No phone number. WhatsApp go ask you to pick the person.",
                 "Kò sí nọ́mbà fóònù. WhatsApp yóò ní kí o yan ẹni náà.",
                 "Babu lambar waya. WhatsApp zai tambaye ka ka zaɓi mutumin.",
                 "Enweghị nọmba ekwentị. WhatsApp ga-ajụ gị ka ị họrọ onye ahụ."],
    "add_phone": ["Add phone", "Add phone", "Fi nọ́mbà kún un", "Ƙara lamba", "Tinye nọmba"],
    "owes_you": ["owes you {m}", "dey owe you {m}", "jẹ ọ́ {m}", "yana da bashinka {m}", "ji gị {m}"],
    "you_owe": ["you owe {m}", "you dey owe {m}", "o jẹ {m}", "kana bin sa {m}", "i ji {m}"],
    "paid_up": ["Paid up", "Don pay finish", "Ti san tán", "Ya biya duka", "Akwụchaala"],
    "due": ["Due {d}", "Go pay {d}", "Yóò san ní {d}", "Zai biya {d}", "Ga-akwụ {d}"],
    "last_item": ["Last: {x}", "Last: {x}", "Ìkẹyìn: {x}", "Na ƙarshe: {x}", "Nke ikpeazụ: {x}"],
    "note_hint": ["Write a note, or what happened (e.g. paid 10k)", "Write note, or wetin happen (e.g. paid 10k)",
                  "Kọ àkíyèsí, tàbí ohun tó ṣẹlẹ̀ (bí paid 10k)", "Rubuta bayani, ko abin da ya faru (misali paid 10k)",
                  "Dee ndetu, ma ọ bụ ihe mere (dịka paid 10k)"],
    "amount": ["Amount (₦)", "Amount (₦)", "Iye owó (₦)", "Adadi (₦)", "Ego (₦)"],
    "item": ["Item", "Wetin you sell", "Ọjà", "Kaya", "Ihe"],
    "paid_now": ["Paid now", "Pay now", "Ó san báyìí", "An biya yanzu", "Akwụọla ugbu a"],
    "on_credit": ["On credit", "On credit", "Àwìn", "Bashi", "Ụgwọ"],
    "will_pay": ["Will pay", "Go pay", "Yóò san", "Zai biya", "Ga-akwụ"],
    "none": ["None", "None", "Kò sí", "Babu", "Ọ dịghị"],
    "today": ["Today", "Today", "Òní", "Yau", "Taa"],
    "yesterday": ["Yesterday", "Yesterday", "Àná", "Jiya", "Ụnyaahụ"],
    "tomorrow": ["Tomorrow", "Tomorrow", "Ọ̀la", "Gobe", "Echi"],
    "friday": ["Friday", "Friday", "Ẹtì", "Juma'a", "Fraịdee"],
    "customer_deleted": ["This customer was deleted.", "Dem don delete this customer.", "A ti pa oníbàárà yìí rẹ́.",
                         "An goge wannan abokin ciniki.", "Ehichapụla onye ahịa a."],
    "confirm_delete_customer": [
        "Delete this customer and the conversation? Their records stay in your book.",
        "Delete this customer and the chat? Wetin you don write for book go remain.",
        "Ṣé kí a pa oníbàárà yìí àti ìjíròrò rẹ̀ rẹ́? Àkọsílẹ̀ owó rẹ̀ yóò wà nínú ìwé rẹ.",
        "A goge abokin ciniki da hirar? Bayanan kuɗinsa za su zauna a littafinka.",
        "Hichapụ onye ahịa a na nkata ya? Ndekọ ego ya ga-anọgide n'akwụkwọ gị."],
    "no_customers": ["No customers yet. They appear here when you record a sale, a debt or a payment with a name.",
                     "No customer yet. Dem go show here when you write sale, debt or payment with name.",
                     "Kò sí oníbàárà síbẹ̀. Wọn yóò hàn níbí nígbà tí o bá kọ ọjà, gbèsè tàbí owó tí wọ́n san pẹ̀lú orúkọ.",
                     "Babu abokin ciniki tukuna. Za su bayyana nan idan ka rubuta sayarwa, bashi ko biya da suna.",
                     "Enweghị onye ahịa ugbu a. Ha ga-apụta ebe a mgbe i dere ahịa, ụgwọ ma ọ bụ ịkwụ ụgwọ nwere aha."],
    "empty_thread": ["Nothing here yet. Record a sale or a payment for {n}.",
                     "Nothing dey here yet. Write sale or payment for {n}.",
                     "Kò sí nǹkan níbí síbẹ̀. Kọ ọjà tàbí owó tí {n} san.",
                     "Babu komai nan tukuna. Rubuta sayarwa ko biyan {n}.",
                     "Ọ dịghị ihe ebe a. Dee ahịa ma ọ bụ ịkwụ ụgwọ maka {n}."],
    "t_sale": ["Sold (paid)", "Sell (dem pay)", "Tà (wọ́n san)", "An sayar (an biya)", "Rere (akwụọla)"],
    "t_credit_sale": ["Sold on credit", "Sell on credit", "Tà ní àwìn", "An sayar bashi", "Rere n'ụgwọ"],
    "t_payment_received": ["Paid me", "Pay me", "San owó fún mi", "Ya biya ni", "Kwụrụ m"],
    "t_expense": ["Spent", "Spend", "Ná owó", "An kashe", "Mefuru"],
    "t_credit_purchase": ["Bought on credit (I owe)", "Buy on credit (I owe)", "Rà ní àwìn (mo jẹ)",
                          "An saya bashi (ina bin)", "Zụtara n'ụgwọ (a na m ji)"],
    "t_payment_made": ["I paid back", "I pay back", "Mo san padà", "Na biya", "Akwụghachiri m"],
    "error": ["Something went wrong. Please try again.", "Something no work. Abeg try again.",
              "Nǹkan kan ò ṣiṣẹ́. Jọ̀wọ́ gbìyànjú lẹ́ẹ̀kan sí i.", "Wani abu ya faru. Da fatan a sake gwadawa.",
              "Ihe adịghị mma. Biko nwaa ọzọ."],
    "offline": ["Can't reach TradeVoice. Check your internet.", "TradeVoice no dey reach. Check your data.",
                "Kò lè dé TradeVoice. Ṣàyẹ̀wò ayélujára rẹ.", "Ba a iya kaiwa TradeVoice ba. Duba intanet ɗinka.",
                "Enweghị ike iru TradeVoice. Lelee ịntanetị gị."],
    "saved_n": ["Saved {n}.", "Don save {n}.", "Ti fi {n} pamọ́.", "An adana {n}.", "Echekwara {n}."],
    "check_save": ["Check, then save", "Check am, then save", "Ṣàyẹ̀wò, kí o tó fi pamọ́", "Duba, sannan ka adana",
                   "Lelee, mgbe ahụ chekwaa"],
    "empty_book": ["Nothing yet. Go to Chat and tell me a sale.", "Nothing yet. Go Chat, tell me wetin you sell.",
                   "Kò sí nǹkan síbẹ̀. Lọ sí Ìjíròrò kí o sọ ọjà tí o tà.", "Babu komai tukuna. Je Hira ka faɗa min abin da ka sayar.",
                   "Ọ dịghị ihe ugbu a. Gaa na Nkata gwa m ihe i rere."],
    "cash_left": ["Cash left after normal spending", "Money wey go remain after normal spending",
                  "Owó tí yóò kù lẹ́yìn ìnáwó", "Kuɗin da zai rage bayan kashe-kashe", "Ego ga-afọdụ mgbe mmefu"],
    "stock_tip": ["Stock up the day before.", "Buy market the day before.", "Ra ọjà ní ọjọ́ tó ṣáájú.",
                  "Saya kaya kwana ɗaya kafin.", "Zụta ngwa ahịa ụbọchị tupu mgbe ahụ."],
    "promised_week": ["Promised this week", "Dem promise to pay this week", "Wọ́n ṣèlérí láti san lọ́sẹ̀ yìí",
                      "Alkawarin biya a wannan makon", "Ha kwere nkwa ịkwụ n'izu a"],
    "forecast_note": ["Forecast = your average sales for each weekday over the last 4 weeks. Simple and explainable, "
                      "not a guarantee.", "Forecast na your average sales for each day for last 4 weeks. E no be promise.",
                      "Àsọtẹ́lẹ̀ yìí jẹ́ àròpọ̀ ọjà rẹ ní ọ̀sẹ̀ mẹ́rin tó kọjá. Kì í ṣe ìdánilójú.",
                      "Hasashe = matsakaicin sayarwarka a makonni 4 da suka wuce. Ba tabbaci ba ne.",
                      "Amụma = nkezi ahịa gị n'izu anọ gara aga. Ọ bụghị nkwa."],
    "why_score": ["Why this score", "Why this score", "Ìdí àmì yìí", "Dalilin wannan maki", "Ihe kpatara akara a"],
    "score_note": ["A simple published formula over your own records, no hidden AI. It helps you talk to a lender, "
                   "cooperative or ajo group; it is not a loan decision.",
                   "Simple formula from your own book, no hidden AI. E help you talk to loan people or cooperative; "
                   "e no be loan decision.",
                   "Ìṣirò rọrùn lórí àkọsílẹ̀ rẹ, kò sí AI tí ó farapamọ́. Ó ràn ọ́ lọ́wọ́ láti bá ẹni tó ń yáni lówó sọ̀rọ̀; "
                   "kì í ṣe ìpinnu owó yíyá.",
                   "Lissafi mai sauƙi daga bayananka, babu AI a ɓoye. Yana taimaka maka magana da mai ba da rance; "
                   "ba shawarar rance ba ce.",
                   "Usoro dị mfe n'ime ndekọ gị, enweghị AI zoro ezo. Ọ na-enyere gị aka ịgwa ndị na-agbazinye ego okwu; "
                   "ọ bụghị mkpebi mbinye ego."],
    "my_year": ["My year so far", "My year so far", "Ọdún mi títí di báyìí", "Shekarata zuwa yanzu", "Afọ m ruo ugbu a"],
    "delete_all": ["Delete all my records", "Delete all my records", "Pa gbogbo àkọsílẹ̀ mi rẹ́", "Goge duk bayanaina",
                   "Hichapụ ndekọ m niile"],
    "privacy": ["Voice notes and photos are read and deleted straight away; only the records are kept. Speech is "
                "turned into text by Intron; the AI that understands your notes and reads your photos runs on our own "
                "NVIDIA Brev GPU. Nothing is saved until you say yes. Reminders are only sent if you press send.",
                "We dey read voice note and photo, then delete am sharp sharp; na only your records we dey keep. "
                "Nothing go save until you talk yes. Reminder no go send unless you press send.",
                "A máa ka ohùn àti fọ́tò, a sì pa wọ́n rẹ́ lẹ́sẹ̀kẹsẹ̀; àkọsílẹ̀ nìkan ni a ń tọ́jú. Kò sí ohun tí a ó "
                "fi pamọ́ títí o fi sọ bẹ́ẹ̀ni. Ìránnilétí kì í lọ àyàfi tí o bá tẹ̀ ẹ́.",
                "Ana karanta murya da hoto sannan a goge su nan take; bayanan kawai ake ajiyewa. Ba a adana komai "
                "sai ka ce eh. Tunatarwa ba ta tafiya sai ka danna aika.",
                "A na-agụ olu na foto ma hichapụ ha ozugbo; naanị ndekọ ka a na-edebe. Ọ dịghị ihe a na-echekwa ruo "
                "mgbe ị kwuru ee. Ncheta anaghị aga ma ọ bụrụ na ị pịaghị zipu."],
    "photo_none": ["I couldn't find money records in this photo. Try a flat page, in good light, whole page in view.",
                   "I no see money records for this photo. Try flat page, better light, whole page.",
                   "Mi ò rí àkọsílẹ̀ owó nínú fọ́tò yìí. Ya ojú ìwé tó tẹ́jú, ní ìmọ́lẹ̀ tó dára.",
                   "Ban ga bayanan kuɗi a hoton nan ba. Gwada shafi a shimfiɗe, a haske mai kyau.",
                   "Ahụghị m ndekọ ego na foto a. Nwaa peeji dị larịị, n'ìhè dị mma."],
    "photo_read": ["I read {n} lines. Check the names and amounts, untick anything wrong, then save.",
                   "I read {n} lines. Check the names and amounts, remove wetin no correct, then save.",
                   "Mo ka ìlà {n}. Ṣàyẹ̀wò orúkọ àti iye owó, yọ èyí tí kò tọ̀nà kúrò, kí o tó fi pamọ́.",
                   "Na karanta layi {n}. Duba sunaye da adadi, cire wanda bai dace ba, sannan ka adana.",
                   "Agụrụ m ahịrị {n}. Lelee aha na ego, wepụ nke na-ezighi ezi, mgbe ahụ chekwaa."],
    "cancelled": ["Cancelled", "Cancelled", "A ti fagilé", "An soke", "Akagbuola"],
    "remind_none": ["{n} doesn't owe you anything 🎉", "{n} no dey owe you 🎉", "{n} kò jẹ ọ́ ní nǹkankan 🎉",
                    "{n} ba shi da bashinka 🎉", "{n} ejighị gị ụgwọ 🎉"],
    "nobody_owes": ["Nobody owes you 🎉", "Nobody dey owe you 🎉", "Kò sí ẹni tó jẹ ọ́ 🎉", "Babu mai bashinka 🎉",
                    "Onweghị onye ji gị ụgwọ 🎉"],
    "you_owe_nobody": ["You owe nobody 🎉", "You no owe anybody 🎉", "O kò jẹ ẹnikẹ́ni 🎉", "Ba ka da bashin kowa 🎉",
                       "I jighị onye ọ bụla ụgwọ 🎉"],
    "wd_0": ["Monday", "Monday", "Ajé", "Litinin", "Mọnde"],
    "wd_1": ["Tuesday", "Tuesday", "Ìṣẹ́gun", "Talata", "Tiuzdee"],
    "wd_2": ["Wednesday", "Wednesday", "Ọjọ́rú", "Laraba", "Wenezdee"],
    "wd_3": ["Thursday", "Thursday", "Ọjọ́bọ̀", "Alhamis", "Tọọzdee"],
    "wd_4": ["Friday", "Friday", "Ẹtì", "Juma'a", "Fraịdee"],
    "wd_5": ["Saturday", "Saturday", "Àbámẹ́ta", "Asabar", "Satọdee"],
    "wd_6": ["Sunday", "Sunday", "Àìkú", "Lahadi", "Sọndee"],
    "sp_Record-keeping consistency": ["Record-keeping consistency", "How often you write", "Bí o ṣe ń kọ̀wé déédéé",
                                      "Rubutu akai-akai", "Ide ndekọ mgbe niile"],
    "sp_Profitability": ["Profitability", "Profit", "Èrè", "Riba", "Uru"],
    "sp_Debt collection": ["Debt collection", "Debt wey you collect", "Gbígba gbèsè", "Karɓar bashi", "Ịnata ụgwọ"],
    "sp_History length": ["History length", "How long you don write", "Gígùn àkọsílẹ̀", "Tsawon bayanai",
                          "Ogologo ndekọ"],
    "band_Strong": ["Strong", "Strong", "Ó lágbára", "Mai ƙarfi", "Siri ike"],
    "band_Building": ["Building", "E dey grow", "Ó ń dàgbà", "Ana ginawa", "Na-eto"],
    "band_Early": ["Early", "Just start", "Ìbẹ̀rẹ̀", "Farko", "Mmalite"],
    "days_avg": ["{d} days of records · average daily sales {m}", "{d} days for book · daily sales average {m}",
                 "Ọjọ́ {d} àkọsílẹ̀ · àròpọ̀ ọjà ojoojúmọ́ {m}", "Kwanaki {d} na bayanai · matsakaicin sayarwa kullum {m}",
                 "Ụbọchị {d} nke ndekọ · nkezi ahịa kwa ụbọchị {m}"],
    "empty_insights": ["Record a few more days, then I can tell you about next week.", "Write for some more days, then I go fit tell you about next week.", "Kọ àkọsílẹ̀ fún ọjọ́ díẹ̀ sí i, lẹ́yìn náà mo lè sọ nípa ọ̀sẹ̀ tó ń bọ̀.", "Ka rubuta na wasu kwanaki, sannan zan iya faɗa maka game da makon gobe.", "Dee ihe ụbọchị ole na ole ọzọ, mgbe ahụ m ga-agwa gị maka izu na-abịa."],
    "empty_profile": ["Your book is empty. Start by recording a sale.", "Your book still empty. Start by writing one sale.", "Ìwé rẹ ṣì ṣófo. Bẹ̀rẹ̀ nípa kíkọ ọjà kan tí o tà.", "Littafinka babu komai. Fara da rubuta wani abin da aka sayar.", "Akwụkwọ gị tọgbọrọ chakoo. Bido site n'ide otu ahịa i rere."],
    "assist_title": ["Ask TradeVoice", "Ask TradeVoice", "Béèrè lọ́wọ́ TradeVoice", "Tambayi TradeVoice", "Jụọ TradeVoice"],
    "assist_hint": ["Tap the mic and ask anything about your business.", "Tap the mic, ask anything about your business.", "Tẹ gbohùngbohùn kí o béèrè ohunkóhun nípa òwò rẹ.", "Taɓa makirufo ka tambayi komai game da kasuwancinka.", "Pịa igwe okwu ka ị jụọ ihe ọ bụla gbasara azụmahịa gị."],
    "listening": ["Listening… tap to send", "I dey hear you… tap to send", "Mo ń gbọ́… tẹ̀ ẹ́ láti fi ránṣẹ́", "Ina saurare… taɓa don aikawa", "A na m ege… pịa ka o ziga"],
    "thinking": ["Thinking…", "I dey think…", "Mo ń ronú…", "Ina tunani…", "A na m eche…"],
    "ask_placeholder": ["Or type a question", "Or type question", "Tàbí kọ ìbéèrè", "Ko rubuta tambaya", "Ma ọ bụ dee ajụjụ"],
    "listening_call": ["Listening… just talk", "I dey hear you… just talk", "Mo ń gbọ́… kàn sọ̀rọ̀", "Ina saurare… kawai yi magana", "A na m ege… naanị kwuo okwu"],
    "speaking": ["Speaking… tap to talk", "I dey talk… tap make you talk", "Mo ń sọ̀rọ̀… tẹ̀ ẹ́ láti sọ̀rọ̀", "Ina magana… taɓa don yin magana", "A na m ekwu… pịa ka ị kwuo"],
    "end_call": ["End", "End", "Parí", "Ƙare", "Kwụsị"],
    "tap_to_talk": ["Tap to talk", "Tap make you talk", "Tẹ̀ ẹ́ láti sọ̀rọ̀", "Taɓa don yin magana", "Pịa ka ị kwuo okwu"],
    # ---- public website (web/landing.html). Short lines only; longer copy stays English until checked by natives.
    "web_open": ["Open TradeVoice", "Open TradeVoice", "Ṣí TradeVoice", "Buɗe TradeVoice", "Mepee TradeVoice"],
    "web_h1": ["Keep your books.<br>Just speak.", "Keep your book.<br>Just talk am.", "Tọ́jú ìwé rẹ.<br>Kàn sọ̀rọ̀.",
               "Riƙe littafinka.<br>Kawai ka yi magana.", "Debe akwụkwọ gị.<br>Naanị kwuo okwu."],
    "web_start": ["Start keeping your books", "Start to keep your book", "Bẹ̀rẹ̀ sí í tọ́jú ìwé rẹ",
                  "Fara riƙe littafinka", "Malite idebe akwụkwọ gị"],
    "web_how": ["See how it works", "See how e dey work", "Wo bí ó ṣe ń ṣiṣẹ́", "Duba yadda yake aiki",
                "Hụ ka o si arụ ọrụ"],
    "web_how_title": ["How it works", "How e dey work", "Bí ó ṣe ń ṣiṣẹ́", "Yadda yake aiki", "Ka o si arụ ọrụ"],
    "web_features": ["Features", "Wetin e fit do", "Ohun tí ó lè ṣe", "Abin da yake yi", "Ihe ọ na-eme"],
    "web_everything": ["Everything a trader needs", "Everything wey trader need", "Gbogbo ohun tí oníṣòwò nílò",
                       "Duk abin da ɗan kasuwa ke bukata", "Ihe niile onye ahịa chọrọ"],
    "web_control": ["You stay in control.", "Na you dey control.", "Ìwọ ni ó ní àṣẹ.", "Kai ne ke da iko.",
                    "Ọ bụ gị na-achịkwa."],
    # ---- year record + tax (tax.py holds the tax facts)
    "tax_title": ["Tax records", "Tax records", "Àkọsílẹ̀ fún owó-orí", "Bayanan haraji", "Ndekọ ụtụ isi"],
    "tax_you": ["This year your book shows sales of {s} and spending of {e}.", "This year your book show say you sell {s} and you spend {e}.", "Lọ́dún yìí, ìwé rẹ fi hàn pé o tà {s}, o sì ná {e}.", "A wannan shekara littafinka ya nuna ka sayar da {s}, ka kashe {e}.", "N'afọ a, akwụkwọ gị na-egosi na i rere {s}, i mefuru {e}."],
    "tax_rent": ["{n} rent and levy payments recorded ({m}). Keep the receipts.", "{n} rent and levy payment dey your book ({m}). Keep the receipts.", "Owó ilé àti owó-ìlú {n} ló wà nínú ìwé rẹ ({m}). Tọ́jú ìwé-ẹ̀rí wọn.", "An rubuta biyan haya da kuɗin kasuwa guda {n} ({m}). Ajiye rasit ɗin.", "Edere ụgwọ ụlọ na levy {n} ({m}). Chekwaa akwụkwọ nnata ha."],
    "tax_record": ["Year record for the tax office", "Year record for tax office", "Àkọsílẹ̀ ọdún fún ilé-iṣẹ́ owó-orí", "Bayanan shekara don ofishin haraji", "Ndekọ afọ maka ụlọ ọrụ ụtụ isi"],
    "tax_facts": ["Tax information", "Tax information", "Ìmọ̀ nípa owó-orí", "Bayani game da haraji", "Ozi gbasara ụtụ isi"],
    "source": ["Source", "Where e come from", "Orísun", "Tushe", "Ebe o si"],
    "year_range": ["{a} to {b} · {d} days recorded", "{a} to {b} · {d} days for book", "{a} sí {b} · ọjọ́ {d} tí a kọ sílẹ̀", "{a} zuwa {b} · kwanaki {d} da aka rubuta", "{a} ruo {b} · ụbọchị {d} e dere"],
    "sales_minus": ["Sales minus spending", "Sales minus spending", "Ọjà tí o tà yọ owó tí o ná", "Sayarwa ban da kashewa", "Ihe i rere wepụ ihe i mefuru"],
    "on_credit": ["{c} on credit", "{c} for credit", "{c} ní àwìn", "{c} bashi", "{c} n'ụgwọ"],
    "stock_note": ["You bought more stock than you sold. Stock you still have is worth money, so this is not the same as a loss.", "You buy more goods pass wetin you sell. The goods wey still dey your shop get value, so e no mean say you lose.", "O ra ọjà ju èyí tí o tà lọ. Ọjà tó ṣì wà lọ́wọ́ rẹ níye lórí, nítorí náà èyí kì í ṣe àdánù.", "Ka sayi kaya fiye da wanda ka sayar. Kayan da ke hannunka suna da daraja, don haka wannan ba asara ba ne.", "Ị zụrụ ngwa ahịa karịa ihe i rere. Ngwa ahịa ka dị gị bara uru, ya mere nke a abụghị mfu."],
    "where_money": ["Where the money went", "Where the money go", "Ibi tí owó lọ", "Inda kuɗin suka tafi", "Ebe ego ahụ gara"],
    "best_month": ["Best month", "Best month", "Oṣù tó dára jù", "Wata mafi kyau", "Ọnwa kacha mma"],
    "no_year": ["No records this year yet.", "No record for this year yet.", "Kò sí àkọsílẹ̀ lọ́dún yìí síbẹ̀.", "Babu bayanai a wannan shekara tukuna.", "Enweghị ndekọ n'afọ a ugbu a."],
    "xt_Rent": ["Rent", "Rent", "Owó ilé", "Haya", "Ụgwọ ụlọ"],
    "xt_Levies & dues": ["Levies and dues", "Levy and dues", "Owó-ìlú àti owó ẹgbẹ́", "Kuɗin kasuwa da na ƙungiya", "Levy na ụgwọ otu"],
    "xt_Power & fuel": ["Power and fuel", "Light and fuel", "Iná àti epo", "Wuta da mai", "Ọkụ na mmanụ"],
    "xt_Transport": ["Transport", "Transport", "Owó ọkọ̀", "Kuɗin mota", "Ụgbọ njem"],
    "xt_Staff": ["Staff", "Workers", "Òṣìṣẹ́", "Ma'aikata", "Ndị ọrụ"],
    "xt_Restock (goods to sell)": ["Restock (goods to sell)", "Buy goods to sell", "Ọjà tí o rà láti tà", "Kayan da ka saya don sayarwa", "Ngwa ahịa ị zụrụ ire"],
    "xt_Other": ["Other", "Other", "Òmíràn", "Wasu", "Ndị ọzọ"],
    # ---- login, Home, Me (redesign)
    "nav_home": ["Home", "Home", "Ilé", "Gida", "Ụlọ"],
    "nav_me": ["Me", "Me", "Èmi", "Ni", "Mụ"],
    "talk_btn": ["Talk", "Talk", "Sọ̀rọ̀", "Magana", "Kwuo"],
    "login_title": ["Your phone number", "Your phone number", "Nọ́mbà fóònù rẹ", "Lambar wayarka", "Nọmba ekwentị gị"],
    "login_why": ["Your book is saved to this number. Use the same number as your WhatsApp.", "Your book go dey for this number. Use the same number wey you dey use for WhatsApp.", "Ìwé rẹ yóò wà lórí nọ́mbà yìí. Lo nọ́mbà WhatsApp rẹ.", "Za a ajiye littafinka a wannan lambar. Yi amfani da lambar WhatsApp ɗinka.", "A ga-echekwa akwụkwọ gị na nọmba a. Jiri nọmba WhatsApp gị."],
    "continue": ["Continue", "Continue", "Tẹ̀síwájú", "Ci gaba", "Gaa n'ihu"],
    "code_title": ["Enter the code", "Put the code", "Tẹ kóòdù náà", "Shigar da lambar", "Tinye koodu ahụ"],
    "code_sent": ["We sent a 6-digit code to {p} on WhatsApp.", "We don send 6-number code to {p} for WhatsApp.", "A ti fi kóòdù oní-nọ́mbà 6 ránṣẹ́ sí {p} lórí WhatsApp.", "Mun aika lambar lamba 6 zuwa {p} a WhatsApp.", "Anyị zigara koodu nọmba 6 na {p} na WhatsApp."],
    "code_not_sent": ["Tap the green button to confirm on WhatsApp.", "Tap the green button to confirm for WhatsApp.", "Tẹ bọ́tìnnì aláwọ̀ ewé láti jẹ́rìí lórí WhatsApp.", "Danna maɓallin kore don tabbatarwa a WhatsApp.", "Pịa bọtịnụ akwụkwọ ndụ iji kwado na WhatsApp."],
    "verify_wa": ["Confirm with WhatsApp", "Confirm with WhatsApp", "Jẹ́rìí pẹ̀lú WhatsApp", "Tabbatar da WhatsApp", "Kwado site na WhatsApp"],
    "verify_wa_hint": ["Opens WhatsApp with a message ready. Just press send, then come back here.", "E go open WhatsApp with message ready. Just press send, come back here.", "Yóò ṣí WhatsApp pẹ̀lú ọ̀rọ̀ tó ti ṣetán. Tẹ ránṣẹ́, kí o sì padà síbí.", "Zai buɗe WhatsApp da saƙo a shirye. Danna aika, sannan ka dawo nan.", "Ọ ga-emepe WhatsApp na ozi dị njikere. Pịa zipu, wee laghachi ebe a."],
    "waiting_wa": ["Waiting for your WhatsApp message…", "We dey wait for your WhatsApp message…", "À ń dúró de ọ̀rọ̀ WhatsApp rẹ…", "Muna jiran saƙon WhatsApp ɗinka…", "Anyị na-echere ozi WhatsApp gị…"],
    "change_number": ["Change number", "Change number", "Yí nọ́mbà padà", "Canza lamba", "Gbanwee nọmba"],
    "demo_code": ["Demo mode: your code is {c}", "Demo mode: your code na {c}", "Ìdánwò: kóòdù rẹ ni {c}", "Gwaji: lambarka ita ce {c}", "Nnwale: koodu gị bụ {c}"],
    "shop_q": ["What is your shop called?", "Wetin be your shop name?", "Kí ni orúkọ ṣọ́ọ̀bù rẹ?", "Menene sunan shagonka?", "Gịnị bụ aha ụlọ ahịa gị?"],
    "your_name": ["Your name", "Your name", "Orúkọ rẹ", "Sunanka", "Aha gị"],
    "start_book": ["Open my book", "Open my book", "Ṣí ìwé mi", "Buɗe littafina", "Mepee akwụkwọ m"],
    "good_morning": ["Good morning", "Good morning", "Ẹ káàárọ̀", "Ina kwana", "Ụtụtụ ọma"],
    "good_afternoon": ["Good afternoon", "Good afternoon", "Ẹ káàsán", "Barka da rana", "Ehihie ọma"],
    "good_evening": ["Good evening", "Good evening", "Ẹ kúùrọ̀lẹ́", "Barka da yamma", "Mgbede ọma"],
    "profit_today": ["Sold minus spent", "Sell minus spend", "Tà yọ ná", "Sayarwa ban da kashewa", "Rere wepụ mefuo"],
    "people_owe": ["People owe you", "People dey owe you", "Àwọn tó jẹ ọ́", "Mutanen da ke da bashinka", "Ndị ji gị ụgwọ"],
    "you_owe_people": ["You owe", "You dey owe", "O jẹ", "Ana binka bashi", "Ị ji ụgwọ"],
    "act_voice": ["Say it", "Talk am", "Sọ ọ́", "Faɗa", "Kwuo ya"],
    "act_snap": ["Snap book", "Snap book", "Ya ìwé", "Ɗauki hoto", "See foto"],
    "act_remind": ["Remind", "Remind", "Rán létí", "Tunatar", "Chetara"],
    "act_share": ["For lender", "For loan", "Fún owó yíyá", "Don rance", "Maka mbinye"],
    "see_all": ["See all", "See all", "Wo gbogbo rẹ̀", "Duba duka", "Hụ ha niile"],
    "hide_amounts": ["Hide amounts", "Hide money", "Fi owó pamọ́", "Ɓoye kuɗi", "Zoo ego"],
    "you_gave": ["You gave", "You give", "O fún", "Ka bayar", "Ị nyere"],
    "you_got": ["You got", "You collect", "O gbà", "Ka karɓa", "Ị natara"],
    "logout": ["Log out", "Log out", "Jáde", "Fita", "Pụọ"],
    "delete_account": ["Delete my account and book", "Delete my account and book", "Pa àkáǹtì àti ìwé mi rẹ́", "Goge asusuna da littafina", "Hichapụ akaụntụ na akwụkwọ m"],
    "sample_data": ["Try with sample records", "Try with sample records", "Gbìyànjú pẹ̀lú àpẹẹrẹ", "Gwada da misalai", "Nwalee na ihe atụ"],
    "sample_note": ["Fills your empty book with 3 weeks of made-up records, marked as demo.", "E go fill your empty book with 3 weeks of sample records (demo).", "Yóò fi àkọsílẹ̀ àpẹẹrẹ ọ̀sẹ̀ mẹ́ta kún ìwé rẹ tó ṣófo (ìdánwò).", "Zai cika littafinka da bayanan misali na makonni 3 (gwaji).", "Ọ ga-etinye ndekọ ihe atụ izu 3 n'akwụkwọ gị efu (nnwale)."],
    "logged_as": ["Logged in as {p}", "You log in as {p}", "O wọlé gẹ́gẹ́ bí {p}", "Ka shiga a matsayin {p}", "Ị banyere dịka {p}"],
    "share_lender": ["Share with a lender", "Share with loan people", "Fi ránṣẹ́ sí ẹni tó ń yáni lówó", "Aika wa mai ba da rance", "Zigara onye na-agbazinye ego"],
    "wrong_score": ["Score looks wrong? Tell us", "Score no correct? Tell us", "Àmì kò tọ̀nà? Sọ fún wa", "Maki ba daidai ba? Faɗa mana", "Akara adịghị mma? Gwa anyị"],
    # ---- lender link, pay link, PIN, CSV, offline
    "queued": ["No internet. Your voice note is saved on this phone and will send by itself when the internet is back.", "No network. Your voice note dey this phone; e go send by itself when network come back.", "Kò sí íńtánẹ́ẹ̀tì. Ohùn rẹ wà lórí fóònù yìí; yóò lọ fúnra rẹ̀ tí íńtánẹ́ẹ̀tì bá dé.", "Babu intanet. An ajiye saƙon muryarka a wayar nan; zai tafi da kansa idan intanet ya dawo.", "Enweghị ịntanetị. Ozi olu gị dị na ekwentị a; ọ ga-eziga onwe ya mgbe ịntanetị lọghachiri."],
    "enter_pin": ["Enter your PIN", "Put your PIN", "Tẹ PIN rẹ", "Shigar da PIN ɗinka", "Tinye PIN gị"],
    "forgot_pin": ["Forgot PIN? Log in again with your number", "You forget PIN? Log in again with your number", "Ṣé o gbàgbé PIN? Wọlé padà pẹ̀lú nọ́mbà rẹ", "Ka manta PIN? Sake shiga da lambarka", "Chefuru PIN? Banye ọzọ site na nọmba gị"],
    "pin_lock": ["PIN lock", "PIN lock", "Títì pẹ̀lú PIN", "Kulle da PIN", "Mkpọchi PIN"],
    "pin_why": ["Ask for a 4-number PIN when TradeVoice opens, so nobody else can see your book on this phone.", "Make TradeVoice ask for 4-number PIN when e open, so nobody else fit see your book for this phone.", "Béèrè PIN oní-nọ́mbà mẹ́rin tí TradeVoice bá ṣí, kí ẹlòmíràn má lè rí ìwé rẹ lórí fóònù yìí.", "Nemi PIN mai lamba 4 idan TradeVoice ya buɗe, don kada wani ya ga littafinka a wannan wayar.", "Rịọ PIN nọmba 4 mgbe TradeVoice mepere, ka onye ọzọ ghara ịhụ akwụkwọ gị na ekwentị a."],
    "choose_pin": ["Choose a PIN", "Choose PIN", "Yan PIN", "Zaɓi PIN", "Họrọ PIN"],
    "new_pin": ["New PIN", "New PIN", "PIN tuntun", "Sabon PIN", "PIN ọhụrụ"],
    "repeat_pin": ["Type it again", "Type am again", "Tún un tẹ̀", "Sake rubutawa", "Pịnye ya ọzọ"],
    "pin_off": ["Turn off PIN", "Off the PIN", "Pa PIN", "Kashe PIN", "Gbanyụọ PIN"],
    "pin_4": ["The PIN is 4 numbers.", "PIN na 4 numbers.", "PIN jẹ́ nọ́mbà mẹ́rin.", "PIN lamba 4 ne.", "PIN bụ nọmba 4."],
    "pin_mismatch": ["The two PINs are not the same.", "The two PIN no be the same.", "PIN méjèèjì kò jọra.", "PIN biyun ba ɗaya ba ne.", "PIN abụọ ahụ adịghị otu."],
    "export_csv": ["Download my book (CSV)", "Download my book (CSV)", "Ṣe ìgbàsílẹ̀ ìwé mi (CSV)", "Sauke littafina (CSV)", "Budata akwụkwọ m (CSV)"],
    "bank_details": ["Bank details for pay links", "Bank details for pay link", "Àlàyé báńkì fún ìjápọ̀ ìsanwó", "Bayanan banki don mahaɗin biya", "Nkọwa ụlọ akụ maka njikọ ịkwụ ụgwọ"],
    "bank_why": ["Reminders include a pay link. Customers see these details, pay by transfer, and tap 'I have paid'. You confirm when the money arrives.", "Reminder go carry pay link. Customer go see these details, transfer, then tap 'I have paid'. You go confirm when money land.", "Ìránilétí ní ìjápọ̀ ìsanwó. Oníbàárà yóò rí àlàyé yìí, yóò fi owó ránṣẹ́, yóò sì tẹ 'Mo ti sanwó'. Ìwọ yóò jẹ́rìí nígbà tí owó bá dé.", "Tunatarwa na da mahaɗin biya. Abokin ciniki zai ga bayanan nan, ya tura kuɗi, ya danna 'Na biya'. Kai ka tabbatar idan kuɗin ya iso.", "Ncheta nwere njikọ ịkwụ ụgwọ. Onye ahịa ga-ahụ nkọwa ndị a, zipu ego, pịa 'Akwụọla m'. Ị ga-akwado mgbe ego ahụ bịarutere."],
    "paystack_on": ["Customers can pay by card, transfer or USSD with Paystack, and the debt updates by itself. Bank details are a second option.", "Customer fit pay with card, transfer or USSD for Paystack, and the debt go update by itself. Bank details na second option.", "Oníbàárà lè sanwó pẹ̀lú káàdì, ìfiránṣẹ́ tàbí USSD lórí Paystack, gbèsè yóò sì yí padà fúnra rẹ̀.", "Abokin ciniki zai iya biya da kati, tura kuɗi ko USSD ta Paystack, bashin zai sabunta da kansa.", "Onye ahịa nwere ike ịkwụ site na kaadị, nnyefe ma ọ bụ USSD na Paystack, ụgwọ ga-emelite onwe ya."],
    "bank_name": ["Bank", "Bank", "Báńkì", "Banki", "Ụlọ akụ"],
    "account_number": ["Account number", "Account number", "Nọ́mbà àkáǹtì", "Lambar asusu", "Nọmba akaụntụ"],
    "account_name": ["Account name", "Account name", "Orúkọ àkáǹtì", "Sunan asusu", "Aha akaụntụ"],
    "share_what": ["The lender sees your record score, sales, spending, money owed to you and your weekly summary. They do not see your customers' phone numbers or your voice notes.", "The loan person go see your score, sales, spending, money wey people owe you and your weekly summary. Dem no go see your customers' phone numbers or your voice notes.", "Ẹni tó ń yáni lówó yóò rí àmì rẹ, ọjà tí o tà, owó tí o ná, owó tí wọ́n jẹ ọ́ àti àkópọ̀ ọ̀sẹ̀. Wọn kò ní rí nọ́mbà fóònù àwọn oníbàárà rẹ tàbí ohùn rẹ.", "Mai ba da rance zai ga makinka, sayarwa, kashewa, kuɗin da ake bin ka da taƙaitaccen mako. Ba zai ga lambobin wayar abokan cinikinka ko saƙonnin muryarka ba.", "Onye na-agbazinye ego ga-ahụ akara gị, ihe i rere, ihe i mefuru, ego ndị mmadụ ji gị na nchịkọta izu. Ha agaghị ahụ nọmba ekwentị ndị ahịa gị ma ọ bụ ozi olu gị."],
    "share_how_long": ["For how long?", "For how long?", "Fún ìgbà mélòó?", "Na tsawon wane lokaci?", "Ruo ogologo oge ole?"],
    "one_day": ["1 day", "1 day", "Ọjọ́ 1", "Kwana 1", "Ụbọchị 1"],
    "seven_days": ["7 days", "7 days", "Ọjọ́ 7", "Kwana 7", "Ụbọchị 7"],
    "thirty_days": ["30 days", "30 days", "Ọjọ́ 30", "Kwana 30", "Ụbọchị 30"],
    "share_consent": ["I agree to share my records with this lender. I can stop it at any time.", "I gree make this loan person see my records. I fit stop am any time.", "Mo gbà láti fi àkọsílẹ̀ mi hàn ẹni tó ń yáni lówó yìí. Mo lè dá a dúró nígbàkígbà.", "Na yarda in nuna bayanaina ga wannan mai ba da rance. Zan iya dakatar da shi kowane lokaci.", "Ekwere m ka onye mbinye ego a hụ ndekọ m. Enwere m ike ịkwụsị ya mgbe ọ bụla."],
    "create_link": ["Create the link", "Make the link", "Ṣẹ̀dá ìjápọ̀", "Ƙirƙiri mahaɗi", "Mepụta njikọ"],
    "link_ready": ["Link ready. It stops working on {d}.", "Link don ready. E go stop on {d}.", "Ìjápọ̀ ti ṣetán. Yóò dáwọ́ dúró ní {d}.", "Mahaɗi ya shirya. Zai daina aiki a {d}.", "Njikọ adịla njikere. Ọ ga-akwụsị na {d}."],
    "my_links": ["My links", "My links", "Àwọn ìjápọ̀ mi", "Mahaɗaina", "Njikọ m"],
    "views": ["views", "views", "ìwò", "kallo", "nlele"],
    "stop_sharing": ["Stop", "Stop am", "Dá a dúró", "Dakatar", "Kwụsị"],
    "stopped": ["Ended", "E don end", "Ó ti parí", "Ya ƙare", "Ọ gwụla"],
    "no_links": ["No links yet.", "No link yet.", "Kò sí ìjápọ̀ síbẹ̀.", "Babu mahaɗi tukuna.", "Enweghị njikọ ugbu a."],
    "copy": ["Copy", "Copy", "Ṣàdàkọ", "Kwafi", "Detuo"],
    "send_whatsapp": ["Send on WhatsApp", "Send for WhatsApp", "Fi ránṣẹ́ lórí WhatsApp", "Aika a WhatsApp", "Zipu na WhatsApp"],
    "receipt": ["Receipt", "Receipt", "Ìwé-ẹ̀rí", "Rasit", "Akwụkwọ nnata"],
    "pay_link": ["Pay link", "Pay link", "Ìjápọ̀ ìsanwó", "Mahaɗin biya", "Njikọ ịkwụ ụgwọ"],
    "confirm_paid": ["Money arrived: record it", "Money don land: record am", "Owó ti dé: kọ ọ́ sílẹ̀", "Kuɗi ya iso: rubuta shi", "Ego abịala: dee ya"],
    "recorded": ["Recorded", "E don enter", "A ti kọ ọ́", "An rubuta", "Edere ya"],
    # ---- Ask: example questions per screen (answered exactly from the book)
    "ex_today_1": ["How much did I make this week?", "How much I make this week?", "Èlò ni mo pa lọ́sẹ̀ yìí?", "Nawa na samu a wannan mako?", "Ego ole ka m nwetara n'izu a?"],
    "ex_today_2": ["Who owes me money?", "Who dey owe me?", "Ta ló jẹ mí lówó?", "Su wa ke da bashina?", "Onye ji m ụgwọ?"],
    "ex_today_3": ["What do I need to pay?", "Wetin I go pay?", "Kí ni mo gbọ́dọ̀ san?", "Me zan biya?", "Gịnị ka m ga-akwụ?"],
    "ex_owes_1": ["Who owes me the most?", "Who dey owe me pass?", "Ta ló jẹ mí jù?", "Wa ke da bashina mafi yawa?", "Onye ji m ụgwọ kacha?"],
    "ex_owes_2": ["Who is late?", "Who don late?", "Ta ló ti pẹ́?", "Su wa suka makara?", "Onye egbuola oge?"],
    "ex_owes_3": ["How much does Mama Tunde owe me?", "How much Mama Tunde dey owe me?", "Èlò ni Mama Tunde jẹ mí?", "Nawa Mama Tunde ke da bashina?", "Ego ole ka Mama Tunde ji m?"],
    "ex_insights_1": ["What did I sell most this week?", "Wetin sell pass this week?", "Kí ló tà jù lọ́sẹ̀ yìí?", "Me ya fi sayuwa a wannan mako?", "Gịnị kacha ree n'izu a?"],
    "ex_insights_2": ["Which item gives me the most profit?", "Which item dey give me gain pass?", "Ọjà wo ló ń fún mi ní èrè jù?", "Wane kaya ne ya fi ba ni riba?", "Kedu ihe na-enye m uru kacha?"],
    "ex_insights_3": ["Which day is busiest?", "Which day market dey move pass?", "Ọjọ́ wo ni ọjà ń tà jù?", "Wace rana kasuwa ta fi ci?", "Ụbọchị ole ka ahịa na-aga kacha?"],
    "ex_profile_1": ["What is my record score?", "Wetin be my record score?", "Kí ni àmì àkọsílẹ̀ mi?", "Nawa ne makin bayanaina?", "Gịnị bụ akara ndekọ m?"],
    "ex_profile_2": ["How can I raise my score?", "How I go make my score go up?", "Báwo ni mo ṣe lè gbé àmì mi sókè?", "Yaya zan ƙara makina?", "Kedu ka m ga-esi bulie akara m?"],
    "ex_profile_3": ["Do I pay tax?", "I go pay tax?", "Ṣé mo máa san owó orí?", "Zan biya haraji?", "M ga-akwụ ụtụ isi?"],
    "try_asking": ["Try asking", "Try ask", "Gbìyànjú láti béèrè", "Gwada tambaya", "Nwalee ịjụ"],
    "tax_info_note": ["General information based on available guidance. Confirm your obligations with a qualified tax professional.", "General information from wetin government don talk. Confirm with tax professional before you pay.", "Ìmọ̀ gbogbogbò láti inú ìtọ́sọ́nà tó wà. Jẹ́rìí ojúṣe rẹ pẹ̀lú ògbóǹtarìgì owó-orí.", "Bayani na gaba ɗaya daga jagororin da ake da su. Tabbatar da nauyinka da ƙwararren masanin haraji.", "Ozi izugbe sitere na ntụziaka dị. Kwado ọrụ gị na onye ọkachamara ụtụ isi."],
    "trust_1": ["Nothing is saved until you confirm.", "Nothing go save until you confirm.", "A kò ní kọ nǹkan sílẹ̀ títí o fi jẹ́rìí.", "Ba a adana komai sai ka tabbatar.", "Ọ dịghị ihe a na-echekwa ruo mgbe ị kwadoro."],
    "trust_2": ["Your voice note is processed and then deleted.", "We dey process your voice note, then we delete am.", "A máa ka ohùn rẹ, lẹ́yìn náà a ó pa á rẹ́.", "Ana sarrafa saƙon muryarka sannan a goge shi.", "A na-edozi ozi olu gị ma hichapụ ya."],
    "trust_3": ["You can delete your records at any time.", "You fit delete your records any time.", "O lè pa àkọsílẹ̀ rẹ rẹ́ nígbàkígbà.", "Za ka iya goge bayananka kowane lokaci.", "Ị nwere ike ihichapụ ndekọ gị mgbe ọ bụla."],
    # ---- refinement plan: confirmation card, home, customers, trust
    "account_deleted": ["Account deleted", "Account don delete", "A ti pa àkáǹtì rẹ́", "An goge asusun", "Ehichapụla akaụntụ"],
    "add_amount": ["Add amount", "Add the money", "Fi iye owó kún un", "Ƙara adadin kuɗi", "Tinye ego ole"],
    "balance_after": ["Balance {m}", "Balance {m}", "Èyí tó kù {m}", "Saura {m}", "Ihe fọdụrụ {m}"],
    "change": ["Change", "Change am", "Yí i padà", "Canza", "Gbanwee"],
    "check": ["Check", "Check am", "Ṣàyẹ̀wò", "Duba", "Lelee"],
    "collect": ["Collect", "Collect", "Gbà owó", "Karɓi kuɗi", "Nata ego"],
    "copied": ["Copied", "E don copy", "A ti ṣàdàkọ", "An kwafa", "Edetuola"],
    "customer": ["Customer", "Customer", "Oníbàárà", "Abokin ciniki", "Onye ahịa"],
    "days_overdue": ["{n} days overdue", "{n} days don pass", "Ó ti pẹ́ ní ọjọ́ {n}", "Kwanaki {n} da wuce lokaci", "Ụbọchị {n} gafere"],
    "delete_account_why": ["Your records, customers and settings are deleted for good. Type DELETE to confirm.", "Your records, customers and settings go delete forever. Type DELETE to confirm.", "Àkọsílẹ̀, àwọn oníbàárà àti ètò rẹ yóò pa rẹ́ pátápátá. Tẹ DELETE láti jẹ́rìí.", "Za a goge bayananka, abokan ciniki da saituna har abada. Rubuta DELETE don tabbatarwa.", "A ga-ehichapụ ndekọ gị, ndị ahịa na ntọala ruo mgbe ebighị ebi. Dee DELETE iji kwado."],
    "delete_customer_why": ["The customer and the conversation are removed. Records already counted stay in your totals.", "The customer and the chat go comot. Records wey don count go still dey your totals.", "A ó yọ oníbàárà àti ìjíròrò rẹ̀ kúrò. Àkọsílẹ̀ tó ti wà nínú àròpọ̀ yóò dúró.", "Za a cire abokin ciniki da hirar. Bayanan da aka riga aka lissafa za su tsaya a jimilla.", "A ga-ewepụ onye ahịa na mkparịta ụka. Ndekọ agụọla ga-anọgide na ngụkọta gị."],
    "delete_record": ["Delete this record?", "Delete this record?", "Pa àkọsílẹ̀ yìí rẹ́?", "Goge wannan bayani?", "Hichapụ ndekọ a?"],
    "delete_record_why": ["It will be removed from your book and your totals.", "E go comot from your book and your totals.", "A ó yọ ọ́ kúrò nínú ìwé àti àròpọ̀ rẹ.", "Za a cire shi daga littafinka da jimilla.", "A ga-ewepụ ya n'akwụkwọ gị na ngụkọta."],
    "done": ["Done", "Done", "Ó ti parí", "An gama", "Emechaala"],
    "due_label": ["Pay by", "Pay by", "San ní", "Biya kafin", "Kwụọ tupu"],
    "due_today": ["Promised today", "Promise na today", "Ìlérí òní", "Alkawarin yau", "Nkwa taa"],
    "empty_home": ["Tell me your first sale.", "Tell me your first sale.", "Sọ ọjà àkọ́kọ́ tí o tà fún mi.", "Faɗa min abin da ka fara sayarwa.", "Gwa m ahịa mbụ i rere."],
    "empty_home_title": ["Your book is empty", "Your book empty", "Ìwé rẹ ṣófo", "Littafinka babu komai", "Akwụkwọ gị tọgbọ chakoo"],
    "empty_insights_title": ["Not enough records yet", "Records never reach", "Àkọsílẹ̀ kò tíì tó", "Bayanai ba su isa ba tukuna", "Ndekọ ezubeghị"],
    "expected": ["expected", "e fit come", "ni a retí", "ake tsammani", "a na-atụ anya"],
    "just_talk": ["Don't know where to start? Just talk.", "You no know where to start? Just talk.", "O kò mọ ibi tí o máa bẹ̀rẹ̀? Kàn sọ̀rọ̀.", "Ba ka san inda za ka fara ba? Kawai yi magana.", "Amaghị ebe ị ga-amalite? Naanị kwuo okwu."],
    "late_n": ["{n} late", "{n} don late", "{n} ti pẹ́", "{n} sun makara", "{n} egbuola oge"],
    "lender_report": ["Lender report", "Report for loan", "Ìròyìn fún owó yíyá", "Rahoto don rance", "Akụkọ maka mbinye"],
    "link_stopped": ["Link stopped", "Link don stop", "A ti dá ìjápọ̀ dúró", "An dakatar da mahaɗin", "Akwụsịla njikọ"],
    "money_in": ["Money in"] * 5,
    "money_net": ["Money in − money out"] * 5,
    "money_out": ["Money out"] * 5,
    "no_customers_hint": ["Your customers appear here when you record a sale.", "Your customers go show here when you record sale.", "Àwọn oníbàárà rẹ yóò hàn níbí tí o bá kọ ọjà sílẹ̀.", "Abokan cinikinka za su bayyana a nan idan ka rubuta sayarwa.", "Ndị ahịa gị ga-apụta ebe a mgbe ị dere ahịa."],
    "no_match": ["Nobody matches.", "Nobody match.", "Kò sí ẹni tó bá a mu.", "Babu wanda ya dace.", "Ọ dịghị onye dabara."],
    "not_said": ["Not said", "You no talk am", "O kò sọ ọ́", "Ba a faɗa ba", "Ekwughị ya"],
    "nothing_saved": ["Nothing is saved until you confirm.", "Nothing go save until you confirm.", "A kò ní kọ nǹkan sílẹ̀ títí o fi jẹ́rìí.", "Ba a adana komai sai ka tabbatar.", "Ọ dịghị ihe a na-echekwa ruo mgbe ị kwadoro."],
    "or": ["or", "or", "tàbí", "ko", "ma ọ bụ"],
    "owes_you_short": ["owes you", "dey owe you", "jẹ ọ́", "yana da bashinka", "ji gị"],
    "pin_removed": ["PIN turned off", "PIN don off", "A ti pa PIN", "An kashe PIN", "Agbanyụọla PIN"],
    "pin_set": ["PIN set", "PIN don set", "A ti ṣe PIN", "An saita PIN", "Edozila PIN"],
    "quantity": ["How many", "How many", "Mélòó", "Nawa", "Ole"],
    "record_first": ["Record your first sale", "Record your first sale", "Kọ ọjà àkọ́kọ́ sílẹ̀", "Rubuta sayarwarka ta farko", "Dee ahịa mbụ gị"],
    "reminder": ["Reminder", "Reminder", "Ìránilétí", "Tunatarwa", "Ncheta"],
    "sample_added": ["Sample records added", "Sample records don enter", "A ti fi àpẹẹrẹ kún un", "An ƙara misalai", "Etinyela ihe atụ"],
    "saved": ["Saved", "E don save", "A ti kọ ọ́", "An adana", "Echekwala"],
    "saved_book": ["Saved to your book", "E don enter your book", "A ti kọ ọ́ sínú ìwé rẹ", "An adana a littafinka", "Echekwala n'akwụkwọ gị"],
    "scan_book": ["Scan book", "Snap book", "Ya ìwé", "Ɗauki hoton littafi", "See foto akwụkwọ"],
    "see_who": ["See who owes you", "See who dey owe you", "Wo àwọn tó jẹ ọ́", "Duba masu bashinka", "Hụ ndị ji gị ụgwọ"],
    "send_again": ["Send again", "Send again", "Tún un fi ránṣẹ́", "Sake aikawa", "Zipu ọzọ"],
    "sending_saved": ["Sending your saved voice notes…", "We dey send your saved voice notes…", "À ń fi àwọn ohùn tí a fi pamọ́ ránṣẹ́…", "Ana aika saƙonnin muryarka da aka ajiye…", "A na-eziga ozi olu gị echekwara…"],
    "sold_credit_today": ["Sold on credit today: {m}", "Credit sale today: {m}", "Àwìn òní: {m}", "Bashin da aka bayar yau: {m}", "Ahịa ụgwọ taa: {m}"],
    "tell_tv": ["Tell TradeVoice", "Tell TradeVoice", "Sọ fún TradeVoice", "Faɗa wa TradeVoice", "Gwa TradeVoice"],
    "to_collect": ["Money to collect", "Money to collect", "Owó tí o máa gbà", "Kuɗin da za ka karɓa", "Ego ị ga-anata"],
    "try_example": ["I sold three bags of rice to Mama Tunde for 45,000 naira.", "I sell three bags of rice give Mama Tunde for 45,000 naira.", "Mo ta àpò ìrẹsì mẹ́ta fún Mama Tunde ní ẹgbẹ̀rún márùndínláàádọ́ta náírà.", "Na sayar wa Mama Tunde buhun shinkafa uku kan naira dubu arba'in da biyar.", "M rere Mama Tunde akpa osikapa atọ na puku naira iri anọ na ise."],
    "try_saying": ["Try saying:", "Try talk:", "Gbìyànjú láti sọ pé:", "Gwada faɗin:", "Nwalee ịsị:"],
    "type_label": ["What happened", "Wetin happen", "Kí ló ṣẹlẹ̀", "Me ya faru", "Gịnị mere"],
    "understanding": ["Understanding…", "I dey understand am…", "Mo ń gbọ́ ọ yé…", "Ina fahimta…", "M na-aghọta…"],
    "understood": ["I understood", "Wetin I hear", "Ohun tí mo gbọ́", "Abin da na fahimta", "Ihe m ghọtara"],
    "unit": ["Unit", "Unit", "Ìwọ̀n", "Ma'auni", "Ụdị"],
    "unsure_amount": ["I didn't hear an amount. How much was it?", "I no hear the money. How much?", "Mi ò gbọ́ iye owó. Èlò ni?", "Ban ji adadin kuɗi ba. Nawa ne?", "Anụghị m ego ole. Ego ole ka ọ bụ?"],
    "unsure_customer": ["Who is this for?", "Na for who?", "Ti ta ni?", "Na wane ne?", "Nke onye?"],
    "unsure_due": ["No payment date was said. Add one, or save without it.", "You no talk when dem go pay. Add date, or save like that.", "O kò sọ ọjọ́ ìsanwó. Fi ọjọ́ kún un, tàbí kọ ọ́ bẹ́ẹ̀.", "Ba a faɗi ranar biya ba. Ƙara rana, ko adana haka.", "Ekwughị ụbọchị ịkwụ ụgwọ. Tinye ya, ma ọ bụ chekwaa otu a."],
    "unsure_type": ["I wasn't sure what kind of record this is. Please check.", "I no sure which kind record be this. Abeg check.", "Mi ò dá mi lójú irú àkọsílẹ̀ tí èyí jẹ́. Jọ̀wọ́ ṣàyẹ̀wò.", "Ban tabbata wane irin bayani ne ba. Da fatan ka duba.", "O doghị m anya ụdị ndekọ nke a bụ. Biko lelee."],
    "you_are_owed": ["You are owed", "Dem dey owe you", "Wọ́n jẹ ọ́", "Kana bin bashi", "A ji gị ụgwọ"],
    "you_owe_after": ["You owe {m}", "You dey owe {m}", "O jẹ {m}", "Ana binka {m}", "Ị ji {m}"],
    "you_owe_short": ["you owe", "you dey owe", "o jẹ", "ana binka", "ị ji"],
    "you_owe_them": ["You owe them", "You dey owe am", "O jẹ wọ́n", "Ana binka bashi", "Ị ji ha ụgwọ"],
    "you_send": ["Check it, then send it yourself", "Check am, then send am yourself", "Ṣàyẹ̀wò rẹ̀, kí o fi ránṣẹ́ fúnra rẹ", "Duba, sannan ka aika da kanka", "Lelee ya, wee zipu ya n'onwe gị"],
    # ---- credit limit
    "over_limit_title": ["Above the credit limit", "E pass the credit limit", "Ó ju òpin àwìn lọ", "Ya wuce iyakar bashi", "Ọ karịrị oke ụgwọ"],
    "over_limit_body": ["{who} owes {bal}. This sale makes it {after}. Limit: {lim}.", "{who} dey owe {bal}. This sale go make am {after}. Limit na {lim}.", "{who} jẹ {bal}. Ọjà yìí yóò mú un dé {after}. Òpin: {lim}.", "{who} yana da bashin {bal}. Wannan sayarwa za ta kai {after}. Iyaka: {lim}.", "{who} ji {bal}. Ahịa a ga-eme ya {after}. Oke: {lim}."],
    "sell_anyway": ["Sell anyway", "Sell am anyway", "Tà á bẹ́ẹ̀", "Sayar duk da haka", "Ree ya n'agbanyeghị"],
    "over_limit_short": ["Over limit", "Pass limit", "Ó ju òpin", "Ya wuce iyaka", "Karịrị oke"],
    "limit_of": ["Limit {m}", "Limit {m}", "Òpin {m}", "Iyaka {m}", "Oke {m}"],
    "credit_limit": ["Credit limit (₦)", "Credit limit (₦)", "Òpin àwìn (₦)", "Iyakar bashi (₦)", "Oke ụgwọ (₦)"],
    "no_limit": ["No limit", "No limit", "Kò sí òpin", "Babu iyaka", "Enweghị oke"],
    "credit_limit_why": ["The most this customer may owe you. TradeVoice warns you before a sale goes over it.", "The most money wey this customer fit owe you. TradeVoice go warn you before any sale pass am.", "Iye tó pọ̀ jù tí oníbàárà yìí lè jẹ ọ́. TradeVoice yóò kìlọ̀ fún ọ kí ọjà tó kọjá rẹ̀.", "Mafi yawan bashin da wannan abokin ciniki zai iya ɗauka. TradeVoice za ta faɗakar da kai kafin sayarwa ta wuce.", "Ego kacha nke onye ahịa a nwere ike iji gị. TradeVoice ga-adọ gị aka ná ntị tupu ahịa agafee ya."],
    # ---- margins + suppliers
    "margin_title": ["Margin per item", "Wetin each item dey give you", "Èrè lórí ọjà kọ̀ọ̀kan", "Riba a kan kowane kaya", "Uru n'ihe ọ bụla"],
    "per_unit": ["per {u}", "per {u}", "fún {u} kan", "kowane {u}", "otu {u}"],
    "one": ["one", "one", "kan", "ɗaya", "otu"],
    "sell_buy": ["Sell {s} · buy {b}", "Sell {s} · buy {b}", "Tà {s} · rà {b}", "Sayarwa {s} · saya {b}", "Ree {s} · zụta {b}"],
    "margin_empty": ["Say how many you buy and sell (\"I buy 10 bags rice 120k\") and TradeVoice shows what each item earns you.", "Talk how many you buy and sell (\"I buy 10 bags rice 120k\") and TradeVoice go show wetin each item dey give you.", "Sọ iye tí o rà àti tí o tà (\"Mo ra àpò ìrẹsì 10 ní 120k\"), TradeVoice yóò fi èrè ọjà kọ̀ọ̀kan hàn.", "Faɗi yawan da ka saya da wanda ka sayar (\"Na sayi buhun shinkafa 10 kan 120k\"), TradeVoice za ta nuna ribar kowane kaya.", "Kwuo ole ị zụrụ na ole ị rere (\"Azụrụ m akpa osikapa 10 na 120k\"), TradeVoice ga-egosi uru ihe ọ bụla."],
    "cheapest_title": ["Cheapest supplier", "Who dey sell cheap pass", "Olùtajà tó din jù", "Mai sayarwa mafi arha", "Onye na-ere kacha ọnụ ala"],
    "save_per": ["Save {m} per {u}", "Save {m} per {u}", "Fi {m} pamọ́ fún {u} kan", "Ajiye {m} kowane {u}", "Chekwaa {m} otu {u}"],
    "ex_insights_4": ["Who sells rice cheapest?", "Who dey sell rice cheap pass?", "Ta ló ń ta ìrẹsì tó din jù?", "Wa ke sayar da shinkafa mafi arha?", "Onye na-ere osikapa kacha ọnụ ala?"],
    "statement_label": ["Statement", "Statement", "Àkọsílẹ̀", "Bayanin asusu", "Nkọwa akaụntụ"],
    "send_statement": ["Send them a statement", "Send them statement", "Fi àkọsílẹ̀ ránṣẹ́ sí wọn", "Aika musu bayanin asusu", "Zigara ha nkọwa akaụntụ"],
    # ---- repeat orders
    "usual_today": ["Usual orders today", "Wetin people dey usually buy today", "Ọjà tí wọ́n máa ń rà lónìí", "Odar da aka saba yau", "Ihe a na-azụkarị taa"],
    "record_it": ["Record it", "Write am", "Kọ ọ́", "Rubuta", "Dee ya"],
    "usual_note": ["They bought this on the same day for {n} weeks. Nothing is saved until you confirm.", "Dem don buy am the same day for {n} weeks. Nothing go save until you confirm.", "Wọ́n ti rà á ní ọjọ́ kan náà fún ọ̀sẹ̀ {n}. A kò ní kọ ọ́ títí o fi jẹ́rìí.", "Sun saya a rana ɗaya har makonni {n}. Ba a adana komai sai ka tabbatar.", "Ha zụrụ ya n'otu ụbọchị izu {n}. Ọ dịghị ihe a na-echekwa ruo mgbe ị kwadoro."],
    "on_credit_btn": ["On credit", "For credit", "Ní àwìn", "Bashi", "N'ụgwọ"],
    "code_fallback": ["WhatsApp couldn't send the code right now, so here it is:", "WhatsApp no fit send the code now, so see am here:", "WhatsApp kò lè fi kóòdù ránṣẹ́ báyìí, òun nìyí:", "WhatsApp ba zai iya aika lambar yanzu ba, ga ta nan:", "WhatsApp enweghị ike iziga koodu ugbu a, nke a bụ ya:"],
    "your_code": ["Your code: {c}", "Your code: {c}", "Kóòdù rẹ: {c}", "Lambarka: {c}", "Koodu gị: {c}"],
    "consent": [
        "I agree that my voice note / photo is processed by AI to create my records. "
        "The audio or photo is deleted right after it is read.",
        "I gree make AI read my voice note / photo to write my records. Dem go delete the voice or photo after.",
        "Mo gbà kí AI ka ohùn tàbí fọ́tò mi láti kọ àkọsílẹ̀ mi. Wọn yóò pa ohùn tàbí fọ́tò náà rẹ́ lẹ́yìn náà.",
        "Na yarda AI ta karanta muryata ko hotona don rubuta bayanaina. Za a goge muryar ko hoton bayan haka.",
        "Ekwere m ka AI gụọ olu m ma ọ bụ foto m iji dee ndekọ m. A ga-ehichapụ ha mgbe e mechara.",
    ],
}


# Direction per language, so a right-to-left language (e.g. Arabic-script Hausa, Ajami) can be added later.
DIRECTION = {lang: "ltr" for lang in LANGS}
CODES = {"English": "en", "Pidgin": "pcm", "Yoruba": "yo", "Hausa": "ha", "Igbo": "ig"}


def t(key, lang):
    """Word for `key` in `lang`. Missing language or empty entry -> English; unknown key -> "" (never the key)."""
    values = UI.get(key)
    if not values:
        return ""
    lang = choose(lang)
    v = values[TABLE_LANGS.index(lang)] if TABLE_LANGS.index(lang) < len(values) else ""
    return v or values[0]
